### ISSUE TITLE
KeyError: 'webhook' 

### ISSUE THREAD

**Issue by gjvetten** [fwestenberg/reolink_dev#125]
I have below error in the log. Hacs installed successfully, Integration installed successfully, everything looks okay but no camera entities.

(2021-01-10 21:38:10 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Tuin for reolink_dev Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/reolink_dev/init.py", line 70, in async_setup_entry webhook_id = await register_webhook(hass, base.event_id)
File "/config/custom_components/reolink_dev/init.py", line 155, in register_webhook handlers = hass.data["webhook"]).
KeyError: 'webhook'

Any idea or suggestion? Removed and reinstalled Hacs and Integrations but without succes.

**Comment by Adeber** [comment]
Hi, I have the same issue (v0.10) installed with HACS into the last stable HA version

**Comment by badstraw360** [comment]
I'm having the same problem, and I just installed HA from scratch.

**Comment by fwestenberg** [comment]
Fixed in v0.12. Please reopen if not!
