### ISSUE TITLE
Error setting up entry

### ISSUE THREAD

**Issue by oangelo** [fwestenberg/reolink_dev#162]
**Describe the bug**
A clear and concise description of what the bug is. Please make sure this bug is NOT about the Reolink HACS integration, only for the new Reolink HA integration.

I can sucessfuly add a new camera, but no entity/device is created.

**To Reproduce**
Steps to reproduce the behavior. Please provide the error from the log if possible.

Add a new camera, on the UI says everything is fine, but an error shows in the log:
`2021-03-04 09:17:44 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Dome5mp for reolink_dev
Traceback (most recent call last):
  File "/config/custom_components/reolink_dev/__init__.py", line 72, in async_setup_entry
    push = hass.data[DOMAIN][base.push_manager]
KeyError: 'push_manager-EC71DBAC0568'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 248, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/reolink_dev/__init__.py", line 75, in async_setup_entry
    await push.subscribe(base.event_id)
  File "/config/custom_components/reolink_dev/base.py", line 208, in subscribe
    get_url(self._hass, prefer_external=False),
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 117, in get_url
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError
`

**Expected behavior**

See the new camera and sensors on the UI.

**Screenshots**

**Environment:**
Please provide useful information about your environment, like:
 - Home Assistant version: 2021.3.0 (docker)
 - Reolink camera model:  RLC-522
 - Camera firmware number: v2.0.0.647_20031412

**Additional context**

Intalled the integration by HACS.

**Comment by xannor** [comment]
this is related to #164 which has the underlying issue identified and a couple of workarounds until the HA folks provide an answer.
