### ISSUE TITLE
Python error at startup

### ISSUE THREAD

**Issue by brahmafear** [fwestenberg/reolink_dev#169]
**Describe the bug**
Python error on startup for all configured reolink cameras.  

**To Reproduce**
Restart.  Check logs.  

**Expected behavior**
No errors.

**Screenshots**
Log message:
```
Logger: homeassistant.config_entries
Source: helpers/network.py:124
First occurred: 12:43:40 PM (4 occurrences)
Last logged: 12:43:40 PM

Error setting up entry Reo Driveway for reolink_dev
Error setting up entry reo_frontdoor for reolink_dev
Error setting up entry reo_sidedoor for reolink_dev
Error setting up entry reo_backdoor for reolink_dev
Traceback (most recent call last):
  File "/config/custom_components/reolink_dev/__init__.py", line 72, in async_setup_entry
    push = hass.data[DOMAIN][base.push_manager]
KeyError: 'push_manager-EC71DB76E2CA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 248, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/reolink_dev/__init__.py", line 75, in async_setup_entry
    await push.subscribe(base.event_id)
  File "/config/custom_components/reolink_dev/base.py", line 208, in subscribe
    get_url(self._hass, prefer_external=False),
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 84, in get_url
    request_host = _get_request_host()
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 124, in _get_request_host
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError
```

**Environment:**
Please provide useful information about your environment, like:
 - Home Assistant version = latest
 - Reolink camera model = RLC-410-5MP
 - Camera firmware number = v2.0.0.647_20031402

**Additional context**
Protocol RTMP, Stream main, motion timeout 60s, timeout 30s.

**Comment by brahmafear** [comment]
Received exact same error after removing configured camera and re-adding it via integrations page.

**Comment by brahmafear** [comment]
Reolink integration version 0.14

**Comment by brahmafear** [comment]
Duplicate of 164.  Closing.
