### ISSUE TITLE
Api object has no attribute _backlight_state

### ISSUE THREAD

**Issue by apardian** [fwestenberg/reolink_dev#184]
Hi,

I getting this error,
Any ideas?

```
2021-04-13 10:48:54 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 130, in _handle_refresh_interval
    await self.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 161, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 235, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 295, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 310, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 341, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/reolink_dev/camera.py", line 136, in device_state_attributes
    if value == self._base.api.backlight_state:
  File "/usr/local/lib/python3.8/site-packages/reolink/camera_api.py", line 169, in backlight_state
    return self._backlight_state
AttributeError: 'Api' object has no attribute '_backlight_state'
```

**Comment by fwestenberg** [comment]
I just found the bug. It will be fixed in the next release.
