### ISSUE TITLE
Connecting RLC-810A

### ISSUE THREAD

**Issue by shawwellpete** [fwestenberg/reolink_dev#196]
Hello, thank you for taking the time to create this integration. 

I understand there are issues with this camera and H.265 but I am afraid I am falling at the first hurdle. 

When I try to add the integration with these settings 

<img width="408" alt="reolink" src="https://user-images.githubusercontent.com/74064242/119649855-0ad41e00-be1b-11eb-9f89-8eae900b616c.png">

I get this error

<img width="402" alt="error" src="https://user-images.githubusercontent.com/74064242/119649874-0f003b80-be1b-11eb-9687-e8a4594bd9b2.png">

I can access the camera via a browser with the same ip address, username and password so that's not the issue.

Any suggestions?

**Comment by fwestenberg** [comment]
Any info in the HA log file?

**Comment by shawwellpete** [comment]
Now you mention it, yes!

2021-05-26 11:46:42 ERROR (MainThread) [custom_components.reolink_dev.config_flow] Unexpected exception
Traceback (most recent call last):
File "/config/custom_components/reolink_dev/config_flow.py", line 61, in async_step_user
self.info = await self.async_validate_input(self.hass, user_input)
File "/config/custom_components/reolink_dev/config_flow.py", line 126, in async_validate_input
if not await self.base.connect_api():
File "/config/custom_components/reolink_dev/base.py", line 177, in connect_api
await self._base.api.get_ai_state()
AttributeError: 'ReolinkBase' object has no attribute '_base'

**Comment by fwestenberg** [comment]
Is very likely a cache problem, because I fixed this error and updated the release. Please go to HACS, find the Reolink component and click Update info and next the Reinstall button. It helped for me.

**Comment by shawwellpete** [comment]
Update info didn't do it but a reinstall did, thank you very much!

**Comment by shawwellpete** [comment]
Hi I just tried to add another camera and had the same problem. I was copying and pasting the ip address from my browser which then included http:// at the start. 

Thought I'd mention it in case others are as daft as me.

Thanks for the integration @fwestenberg, great work

**Comment by fwestenberg** [comment]
Thanks for your feedback. And as soon as I find the time I hope to improve some things!
