### ISSUE TITLE
Failed to set up

### ISSUE THREAD

**Issue by MikOsle** [fwestenberg/reolink_dev#197]
Hi,
For 3 days my HA has not been able to connect to my two RLC-410-5MP which has been running for half a year without any problems. I can access the cameras from my NAS, computer and phone with no problem. There has been no changes to my HA setup. I have tried to reconnect the cameras, reinstalled the integration and restored the HA to a backup image from before the issue occurred, but nothing helps. Also, I have not been able to finde any errors in the HA log.

- Home Assistant version: 2021.5.5
- Reolink camera model: RLC-410-5MP
- Camera firmware number: v3.0.0.136_20121100

<img width="281" alt="Skærmbillede 2021-05-29 kl  22 59 46" src="https://user-images.githubusercontent.com/46725638/120084580-b4dcd000-c0d1-11eb-84db-d76365401202.png">

**Comment by klint76** [comment]
Did you happen to resolve this issue?, im having the same problem.

Klint

**Comment by ocso** [comment]
Same issue here, I deleted the integrations (2 RLC-410W camera) and downgraded to version 0.16, it started to work again.

**Comment by emkayg** [comment]
Same issue here :( Even with 0.16

**Comment by emkayg** [comment]
Here is the error log I’m seeing:
Traceback (most recent call last):
  File "/config/custom_components/reolink_dev/__init__.py", line 73, in async_setup_entry
    push = hass.data[DOMAIN][base.push_manager]
KeyError: 'push_manager-ec71dbeb6a0e'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/reolink_dev/__init__.py", line 82, in async_setup_entry
    await push.subscribe(base.event_id)
  File "/config/custom_components/reolink_dev/base.py", line 230, in subscribe
    get_url(self._hass, prefer_external=False),
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 116, in get_url
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError
