### ISSUE TITLE
installing RLC-510WA

### ISSUE THREAD

**Issue by piniSolomon** [fwestenberg/reolink_dev#202]
hi after installing the integration I get this error in logs 
```
Logger: homeassistant.config_entries
Source: helpers/network.py:123
First occurred: 11:20:20 AM (1 occurrences)
Last logged: 11:20:20 AM

Error setting up entry Backyard for reolink_dev
Traceback (most recent call last):
  File "/config/custom_components/reolink_dev/__init__.py", line 77, in async_setup_entry
    push = hass.data[DOMAIN][base.push_manager]
KeyError: 'push_manager-ec71db731679'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 248, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/reolink_dev/__init__.py", line 86, in async_setup_entry
    await push.subscribe(base.event_id)
  File "/config/custom_components/reolink_dev/base.py", line 302, in subscribe
    get_url(self._hass, prefer_external=False),
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 83, in get_url
    request_host = _get_request_host()
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 123, in _get_request_host
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError
```

what should I do? I don't have the device or entity after the installation

**Comment by mateuszkielar** [comment]
I've had the same problem. Try setting "Internal URL" in "Configuration" -> "General". I've also set "External URL", but I think this is not needed.

**Comment by piniSolomon** [comment]
WORKED LIKE A  CHARM
@mateuszkielar
