### ISSUE TITLE
Reolink RLC-410-5MP "Failed to set up" Error

### ISSUE THREAD

**Issue by mbender66** [fwestenberg/reolink_dev#208]
Logger: homeassistant.config_entries
Source: helpers/network.py:116
First occurred: 11:46:53 PM (1 occurrences)
Last logged: 11:46:53 PM

Error setting up entry Office for reolink_dev
Traceback (most recent call last):
  File "/config/custom_components/reolink_dev/__init__.py", line 77, in async_setup_entry
    push = hass.data[DOMAIN][base.push_manager]
KeyError: 'push_manager-ec71db6ce862'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/reolink_dev/__init__.py", line 86, in async_setup_entry
    await push.subscribe(base.event_id)
  File "/config/custom_components/reolink_dev/base.py", line 302, in subscribe
    get_url(self._hass, prefer_external=False),
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 116, in get_url
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError

Version | core-2021.6.6
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
Virtual Environment | false
Python Version | 3.8.9
Operating System Family | Linux
Operating System Version | 5.10.45
CPU Architecture | x86_64
Timezone | America/Phoenix

**Comment by nico101010** [comment]
also have the same issue with the RLC410

**Comment by sklein972** [comment]
Same issue with 510A


Logger: homeassistant.config_entries
Source: helpers/network.py:116
First occurred: 10:04:31 PM (1 occurrences)
Last logged: 10:04:31 PM

Error setting up entry Backyard East for reolink_dev
Traceback (most recent call last):
  File "/config/custom_components/reolink_dev/__init__.py", line 77, in async_setup_entry
    push = hass.data[DOMAIN][base.push_manager]
KeyError: 'push_manager-ec71db53d598'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/reolink_dev/__init__.py", line 86, in async_setup_entry
    await push.subscribe(base.event_id)
  File "/config/custom_components/reolink_dev/base.py", line 302, in subscribe
    get_url(self._hass, prefer_external=False),
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 116, in get_url
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError
