### ISSUE TITLE
Reolink integration HA error: NoURLAvailableError

### ISSUE THREAD

**Issue by freginedevices** [fwestenberg/reolink_dev#214]
**Describe the bug**
After i add the Reolink integration via HA Integratons, it shows me a error message on the integration "configuration not succeded". I have SSL https enabled.

**Screenshots**
https://www.dropbox.com/s/73gul8wym34z3eb/reolin-notwork.jpg?dl=0

**Environment:**
 - Home Assistant 2021.7.0
 - Reolink camera model E1 Zoom
 - Camera firmware number v3.0.0.247_21040708

**Additional context**
HA log:
Logger: homeassistant.config_entries
Source: helpers/network.py:116
First occurred: 11:46:53 (1 occurrences)
Last logged: 11:46:53

Error setting up entry Soggiorno for reolink
Traceback (most recent call last):
  File "/config/custom_components/reolink/__init__.py", line 77, in async_setup_entry
    push = hass.data[DOMAIN][base.push_manager]
KeyError: 'push_manager-b0411de071fe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/reolink/__init__.py", line 86, in async_setup_entry
    await push.subscribe(base.event_id)
  File "/config/custom_components/reolink/base.py", line 302, in subscribe
    get_url(self._hass, prefer_external=False),
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 116, in get_url
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError

**Comment by freginedevices** [comment]
I found the solution:
set in HA Configuration->general->Internal url & External Url
and fill with these
internal_url: http://internal_address:8123
external_url: https://duck_dns_alias.duckdns.org

**Comment by fwestenberg** [comment]
Thanks.
