### ISSUE TITLE
"can't configure Camera

### ISSUE THREAD

**Issue by sklein972** [fwestenberg/reolink_dev#230]
Hi,
I'm getting the following:
Logger: homeassistant.config_entries
Source: helpers/network.py:116
First occurred: 9:39:34 AM (1 occurrences)
Last logged: 9:39:34 AM

Error setting up entry back west for reolink_dev
Traceback (most recent call last):
  File "/config/custom_components/reolink_dev/__init__.py", line 77, in async_setup_entry
    push = hass.data[DOMAIN][base.push_manager]
KeyError: 'push_manager-ec71db377f06'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/reolink_dev/__init__.py", line 86, in async_setup_entry
    await push.subscribe(base.event_id)
  File "/config/custom_components/reolink_dev/base.py", line 302, in subscribe
    get_url(self._hass, prefer_external=False),
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 116, in get_url
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError

**Comment by SergiTello** [comment]
I have the same error with 2 cameras, I am surprised that the error appears so quickly and does not give any further information to make any changes.

2021-07-30 19:48:23 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry XXX for reolink_dev
Traceback (most recent call last):
File "/config/custom_components/reolink_dev/__init__.py", line 77, in async_setup_entry
push = hass.data[DOMAIN][base.push_manager]
KeyError: 'push_manager-44EFBF50D925'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/reolink_dev/__init__.py", line 86, in async_setup_entry
await push.subscribe(base.event_id)
File "/config/custom_components/reolink_dev/base.py", line 302, in subscribe
get_url(self._hass, prefer_external=False),
File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 116, in get_url
raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError

**Comment by SergiTello** [comment]
Solved: https://github.com/fwestenberg/reolink_dev/issues/164

 
jdaubs45 commented on 12 Mar
@pniewiadowski Your solution worked for me. Thanks!
Added this to my configuration.yaml:

homeassistant:
customize: !include customize.yaml
internal_url: https://internal_address:8123
external_url: https://duck_dns_alias.duckdns.org
