### ISSUE TITLE
Cant change integration option settings 

### ISSUE THREAD

**Issue by AaronPitts** [fwestenberg/reolink_dev#231]
Describe the bug:
After selecting the camera I wan to change from the integration page. I'm selecting Options which opens the options page for that camera.

When I make any change the change is rejected and I'm presented with test atop the option page that says "User Input malformed".
The above is true for all options selected:
protocol, stream . motion sensor time out and playback range.

To Reproduce
See above

Expected behavior
The options to change to the selected value

Screenshots
[On HA site post](https://community.home-assistant.io/t/cant-change-the-settings-of-my-reolink-cameras/324947)
[Option Page](https://community-assets.home-assistant.io/original/3X/7/a/7af93782a79eda3f486bd2603d9e857b083ccbea.jpeg)
[Option Page With Error](https://community-assets.home-assistant.io/original/3X/b/9/b9a1ca0b3b9dfada9f0a84af7788a23c1948bebd.jpeg)

Environment:
Please provide useful information about your environment, like:
 - Home Assistant version
- Core
Version
core-2021.7.4

- Supervisor
Version
supervisor-2021.06.8
- Host
Hostname :hassio

Operating System
Home Assistant OS 6.1
Deployment
production

Cameras:
 - Reolink camera model: RLC420 5Mp
 - Camera firmware number: 2.0.0.354_1903_1101

Additional context
I'm also seeing errors in my log

Traceback (most recent call last):
  File "/config/custom_components/reolink_dev/__init__.py", line 123, in update_listener
    base.motion_off_delay = entry.options[CONF_MOTION_OFF_DELAY]
KeyError: 'motion_off_delay'
2021-07-26 14:40:14 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/reolink_dev/__init__.py", line 124, in update_listener
    base.playback_months = entry.options[CONF_PLAYBACK_MONTHS]
KeyError: 'playback_months'
2021-07-26 14:40:24 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/reolink_dev/__init__.py", line 123, in update_listener
    base.motion_off_delay = entry.options[CONF_MOTION_OFF_DELAY]
KeyError: 'motion_off_delay'
2021-07-26 14:40:34 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/reolink_dev/__init__.py", line 123, in update_listener
    base.motion_off_delay = entry.options[CONF_MOTION_OFF_DELAY]
KeyError: 'motion_off_delay'

**Comment by apmillen** [comment]
I am also getting the same "User Input malformed" message when trying to change settings.

**Comment by RobertusIT** [comment]
same here, i didn't understand why

and also, how can i create an automation, to get picture and a video, when there is a motion?

**Comment by danielscheidler** [comment]
same here. 

So main-stream is unusable on HA and I have to use sub-stream if I want to use it without delay of 30seconds. But without this option cam is useless for HA.

Remove the cam,  reinstalled HACS and the Integration and finally integrate the cam again. 
Same Error. 

HA: core-2021.8.6
supervisor-2021.09.0

Camera: Reolink RLC-511WA
Config Version: v3.0.0.0
Firmware Version: v3.0.0.177_21012109

**Comment by RobertusIT** [comment]
I migrate with frigate for now. Is very good, anyway this integration was a good option, so please fix it
