### ISSUE TITLE
Cannot open live feed from lovelace card. AttributeError: 'ReolinkCamera' object has no attribute '_input'

### ISSUE THREAD

**Issue by mariusno** [fwestenberg/reolink_dev#235]
**Describe the bug**
When opening the Picture Entity Card Configuration the error occurs. The text "Preview of Camera1 camera" is shown and now live feed is played, error is written to the HA log: "AttributeError: 'ReolinkCamera' object has no attribute '_input'"
(See screenshots)

Config is set to:
Protocol: RTMP
Steam: Tested main and sub
Custom thumbnail path: /

**To Reproduce**
Open the card again.
Stacktrace from HA:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 77, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 511, in get
    return await self.handle(request, camera)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 546, in handle
    stream = await camera.handle_async_mjpeg_stream(request)
  File "/config/custom_components/reolink_dev/camera.py", line 199, in handle_async_mjpeg_stream
    await stream.open_camera(self._input, extra_cmd=self._extra_arguments)
AttributeError: 'ReolinkCamera' object has no attribute '_input'

**Screenshots**
![image](https://user-images.githubusercontent.com/1242583/127556100-de6aa149-bdcd-47ad-91e2-d7218cc48f44.png)
![image](https://user-images.githubusercontent.com/1242583/127556265-488b69f8-795d-468d-b85d-b9c88ded09aa.png)
![image](https://user-images.githubusercontent.com/1242583/127556288-2d4774b5-29fe-4b97-9be1-0b44107677b0.png)
![image](https://user-images.githubusercontent.com/1242583/127556433-d276ad9e-b39e-46b9-9e2b-60b6a17434eb.png)

**Expected behavior**
Live view from camera

**Environment:**
 - Reolink_dev: v0.19
 - Home Assistant version: core-2021.7.4
 - Operating System: Ubuntu 20.04.2 LTS
 - Reolink camera model: RLC-520
 - Camera firmware number: v3.0.0.136_20121112
 - ffmpeg version 4.2.4-1ubuntu0.1

**Comment by dpeluso** [comment]
I'm also getting this error.

**Comment by mariusno** [comment]
I might have been able to solve this issue.
1. Updated to core-2021-8
2. Added "stream:" to configuration (https://www.home-assistant.io/integrations/stream/)
3. Downloaded the v0.19 version again to custom_components

@dpeluso Maybe you can try this to confirm a possible fix?

**Comment by dpeluso** [comment]
Thanks @mariusno this workout does resolve the error for me too. I'm probably expecting to much but still getting a 10sec lag from cams.
