### ISSUE TITLE
820-A | failed to setup

### ISSUE THREAD

**Issue by nmummau** [fwestenberg/reolink_dev#255]
When adding a reolink 820-A to my Home Assistant integration, I get the following. It does detect the name of my camera ("Cam 1") correctly so I'm assuming that it's finding the camera correctly. But I'm unsure what the logs mean.

I tried using the initial "admin" user and password, and then I tried a different user/password. The same error happens for both.

I am using DuckDNS for Home Assistant so that I can connect to my server externally. Not sure if this has anything to do with the error.

Any help would be greatly appreciated since I've been unable to add this 820-A camera using other methods. Before trying this integration I was running into similar issues as mentioned in [47084](https://github.com/home-assistant/core/issues/47084), and that's how I learned about this reolink hacs integration. Unfortunately it too is seeming difficult.

![image](https://user-images.githubusercontent.com/10524529/131237127-83209f05-9157-4b84-8858-94c66759a554.png)

### Logs
```
Log Details (ERROR)
Logger: homeassistant.config_entries
Source: helpers/network.py:123
First occurred: 11:15:21 PM (1 occurrences)
Last logged: 11:15:21 PM

Error setting up entry Cam 1 for reolink_dev
Traceback (most recent call last):
  File "/config/custom_components/reolink_dev/__init__.py", line 77, in async_setup_entry
    push = hass.data[DOMAIN][base.push_manager]
KeyError: 'push_manager-ec71dbe85901'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/reolink_dev/__init__.py", line 86, in async_setup_entry
    await push.subscribe(base.event_id)
  File "/config/custom_components/reolink_dev/base.py", line 302, in subscribe
    get_url(self._hass, prefer_external=False),
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 83, in get_url
    request_host = _get_request_host()
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 123, in _get_request_host
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError
```

**Comment by sklein972** [comment]
Same issue with 510A:
Logger: homeassistant.config_entries
Source: helpers/network.py:116
First occurred: 10:04:31 PM (1 occurrences)
Last logged: 10:04:31 PM

Error setting up entry Backyard East for reolink_dev
Traceback (most recent call last):
  File "/config/custom_components/reolink_dev/__init__.py", line 77, in async_setup_entry
    push = hass.data[DOMAIN][base.push_manager]
KeyError: 'push_manager-ec71db53d598'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/reolink_dev/__init__.py", line 86, in async_setup_entry
    await push.subscribe(base.event_id)
  File "/config/custom_components/reolink_dev/base.py", line 302, in subscribe
    get_url(self._hass, prefer_external=False),
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 116, in get_url
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError

**Comment by alexander-saratovcev** [comment]
Did you try the following approach https://github.com/fwestenberg/reolink_dev/issues/164#issuecomment-792330331?

**Comment by sklein972** [comment]
Worked like a charm! Thank you!
Did anyone get the Person detection into HA? 🙂

________________________________

**Comment by fwestenberg** [comment]
Person detection is an attribute of the binary motion sensor. Closing this issue.
