### ISSUE TITLE
Error Setting up Devices

### ISSUE THREAD

**Issue by bellisnb** [fwestenberg/reolink_dev#270]
### Discussed in https://github.com/fwestenberg/reolink_dev/discussions/269

<div type='discussions-op-text'>

<sup>Originally posted by **bellisnb** September 15, 2021</sup>
Hi, 

Have installed the Reolink add on as per the the setup guide however when coming to add individual devices from my NVR getting the same error in the logs every time.  ERROR SETTING UP ENTRY BACK GARDEN FOR REOLINK_DEV.

This points me to yaml file "_init_.py" Line 77. looking at the async setup entry. Cannot see what the logs are saying is the issue? Any help much appreciated. Pasted log details below. 

Logger: homeassistant.config_entries
Source: helpers/network.py:116
First occurred: 9:52:19 PM (1 occurrences)
Last logged: 9:52:19 PM

Error setting up entry Back Garden for reolink_dev
Traceback (most recent call last):
  File "/config/custom_components/reolink_dev/__init__.py", line 77, in async_setup_entry
    push = hass.data[DOMAIN][base.push_manager]
KeyError: 'push_manager-ec71db1ea38f'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/reolink_dev/__init__.py", line 86, in async_setup_entry
    await push.subscribe(base.event_id)
  File "/config/custom_components/reolink_dev/base.py", line 302, in subscribe
    get_url(self._hass, prefer_external=False),
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 116, in get_url
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError

Thank You 

Nathan </div>

**Comment by fwestenberg** [comment]
This issue is solved here https://github.com/fwestenberg/reolink_dev/discussions/222
