### ISSUE TITLE
RLC-410W Live view (stream) not work

### ISSUE THREAD

**Issue by svsolopov** [fwestenberg/reolink_dev#278]
Error log:
Эта ошибка возникла в кастомной интеграции.

Logger: aiohttp.server
Source: custom_components/reolink_dev/camera.py:200
Integration: Reolink IP camera (documentation, issues)
First occurred: 19:09:24 (2 occurrences)
Last logged: 19:10:36

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 89, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 517, in get
    return await self.handle(request, camera)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 552, in handle
    stream = await camera.handle_async_mjpeg_stream(request)
  File "/config/custom_components/reolink_dev/camera.py", line 200, in handle_async_mjpeg_stream
    await stream.open_camera(self._input, extra_cmd=self._extra_arguments)
AttributeError: 'ReolinkCamera' object has no attribute '_input'

**Comment by StephenGhool** [comment]
You could try deleting the camera and adding it back..also ensure that the camera's ip address is static

**Comment by cpainchaud** [comment]
@svsolopov  please try v0.37. thank you

**Comment by d3m3trius** [comment]
v0.37 is working for me

**Comment by cpainchaud** [comment]
Closed unless requester complains and reopens

**Comment by svsolopov** [comment]
It's work, super :)
