### ISSUE TITLE
Reolink RLC-820a NoURLAvailableError

### ISSUE THREAD

**Issue by SHMarcoG** [fwestenberg/reolink_dev#289]
Hi,

When i try to add an RLC-820a i get the message that the camera is added succesfully, but after that the integration shows up with the message: setup failed, check the logging.
In the logging the following message shows:
Error setting up entry Camera1 for reolink_dev

Traceback (most recent call last):
File "/config/custom_components/reolink_dev/init.py", line 78, in async_setup_entry
push = hass.data[DOMAIN][base.push_manager]
KeyError: 'push_manager-ec71db3575c9'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/reolink_dev/init.py", line 87, in async_setup_entry
await push.subscribe(base.event_id)
File "/config/custom_components/reolink_dev/base.py", line 318, in subscribe
get_url(self._hass, prefer_external=False),
File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 116, in get_url
raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError

Does someone has an idea how to fix this problem?

**Comment by cpainchaud** [comment]
it's a Home Assistant issue : you have not setup a external_url property . this URL will be used by the camera to reach your installation

**Comment by cpainchaud** [comment]
![image](https://user-images.githubusercontent.com/6696638/135593215-00f3cc79-52c6-41f0-9a22-09f70012fd8e.png)
