### ISSUE TITLE
Reolink RLC-520 stream is frozen in the HomeKit

### ISSUE THREAD

**Issue by Nebr88** [fwestenberg/reolink_dev#296]
I have a Reolink RLC-520 camera that works perfectly in the home assistant. I can change between main and sub streams and all works without freezes. As well the integration added an occupation sensor that works well too.

In the HomeKit (via HomeKit integration) only an actual snapshot is shown, but the stream is completely frozen. So the camera is visible in the list, the occupancy sensor works correctly, a snapshot is shown correctly but the stream is stuck. 

FFmpeg integration transfers the stream correctly

Log from Home Assistant after trying to open the stream:
```
Logger: homeassistant.components.homekit.type_cameras
Source: components/homekit/type_cameras.py:464
Integration: HomeKit (documentation, issues)
First occurred: 18:16:36 (1 occurrences)
Last logged: 18:16:36

[004ee3e0-77ed-4880-94a2-8ca2c10bf7cd] Failed to close stream
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/homekit/type_cameras.py", line 464, in stop_stream
    await getattr(stream, shutdown_method)()
  File "/usr/local/lib/python3.9/site-packages/haffmpeg/core.py", line 158, in close
    await self._loop.run_in_executor(None, _close)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/haffmpeg/core.py", line 153, in _close
    self._proc.stdin.write(b"q")
BrokenPipeError: [Errno 32] Broken pipe
```

```
Logger: homeassistant.components.homekit.type_cameras
Source: components/homekit/type_cameras.py:464
Integration: HomeKit (documentation, issues)
First occurred: 18:16:36 (1 occurrences)
Last logged: 18:16:36

[004ee3e0-77ed-4880-94a2-8ca2c10bf7cd] Failed to kill stream
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/homekit/type_cameras.py", line 464, in stop_stream
    await getattr(stream, shutdown_method)()
  File "/usr/local/lib/python3.9/site-packages/haffmpeg/core.py", line 170, in kill
    self._proc.kill()
AttributeError: 'NoneType' object has no attribute 'kill'
```

**Is it possible to resolve the issue and make it work?**

Stream from the Reolink integration:
![IMG_2236](https://user-images.githubusercontent.com/33136303/136414444-73a30c6f-6416-41c1-a2fd-eaf19f9dd611.PNG)

Stream from the FFmpeg integration:
![IMG_2237](https://user-images.githubusercontent.com/33136303/136414453-b5702efc-7029-44f6-9abc-a5fdb7f75979.PNG)

**Comment by xannor** [comment]
I have experienced this as well, I believe it is because HA just forwards the rtsp stream but Home Kit does not like the format. I will see if I can verify this over the weekend. I think homekit wants mjpeg, which would require conversion via ffmpeg, which unless you are running intel hardware, tends to be flakey (at least that has been my experience with PIs)

**Comment by Nebr88** [comment]
If it helps here is my ffmpeg config that works correctly in the HomeKit:

```
ffmpeg:
camera:
  - platform: generic
    name: Hallway ffmpeg
    still_image_url: "http://192.168.0.16/cgi-bin/api.cgi?cmd=Snap&amp;channel=0&amp;rs=wuuPhkmUCeI9WG7C&amp;user=Username&amp;password=Password"
    stream_source: "-re -rtsp_transport tcp -i rtsp://Username:Password@192.168.0.16:554/h264Preview_01_sub"
```

**Comment by Nebr88** [comment]
Just a kind UP for the issue

**Comment by flame4ever** [comment]
I also have the problem, is there a native solution here?
