### ISSUE TITLE
Not able to log in

### ISSUE THREAD

**Issue by koburg** [fwestenberg/reolink_dev#303]
I can not login

tried create new user in camera no luck

updated to lates integration and latest HA version

keep saying `Unexpected error`

**Comment by xannor** [comment]
Have you verified your username and password works from the camera's web interface? if not you may need to double check them, if your camera does not have a web interface then there is a good chance it is not a supported model. Also, if you are running home assistant in a container environemnt (for instance using hassos) then you will have to address the camera via ip or a fully qualified domain name, as it will not resolve simple host names.

Either way, definitely would need more information than the little you have provided so far to even begin to troubleshoot.

**Comment by spf13** [comment]
I'm having the same issue after updating. Camera is RLC-820A.

Everything worked prior to upgrade. Upgraded and noticed that the new sensors we're available and the old motion sensor was unavailable. Removed one camera to re-add hoping it would add all the new sensors and now I can't add it. The other two cameras are still working, albeit without motion sensors.

**Comment by spf13** [comment]
Figured out something. It works fine when I login as admin, but not as another user (even one with full admin rights).

**Comment by kavemang** [comment]
Also having the same issue as these gentlemen but only with my hard wired POE cameras which is weird, my wifi cam does not have this issue of not being able to connect via a user profile ^

**Comment by cpainchaud** [comment]
> Also having the same issue as these gentlemen but only with my hard wired POE cameras which is weird, my wifi cam does not have this issue of not being able to connect via a user profile ^

while issue may be in this integration, we have found no hint that it is the case so far. Don't underestimate the poor quality of Reolink's software :D

**Comment by cpainchaud** [comment]
well, notice that no one in this thread has provided any log of any sort as required per Ticket template.

**Comment by koburg** [comment]
I found one Solution maybe it will work for you also.

I Found there where some leftovers of entities from the camera so the integration did not work with login.
after deleting those it seems to work now.

this must have been when I once deleted the whole integration and after restart HA installed it again.
so it did not deleted all the entities for the camera.

**Comment by kavemang** [comment]
> well, notice that no one in this thread has provided any log of any sort as required per Ticket template.

sorry I just tried here is my log dump from the error 


```
today at 12:23:47 AM2021-12-02 06:23:47 ERROR (MainThread) [custom_components.reolink_dev.config_flow] Unexpected exception
today at 12:23:47 AMTraceback (most recent call last):
today at 12:23:47 AM  File "/usr/lib/python3.9/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
today at 12:23:47 AM    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
today at 12:23:47 AM  File "/usr/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
today at 12:23:47 AM    raise exceptions[0]
today at 12:23:47 AM  File "/usr/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
today at 12:23:47 AM    sock = await self._connect_sock(
today at 12:23:47 AM  File "/usr/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
today at 12:23:47 AM    await self.sock_connect(sock, address)
today at 12:23:47 AM  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
today at 12:23:47 AM    return await fut
today at 12:23:47 AM  File "/usr/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
today at 12:23:47 AM    raise OSError(err, f'Connect call failed {address}')
today at 12:23:47 AMOSError: [Errno 113] Connect call failed ('192.168.0.36', 443)
today at 12:23:47 AM
today at 12:23:47 AMThe above exception was the direct cause of the following exception:
today at 12:23:47 AM
today at 12:23:47 AMTraceback (most recent call last):
today at 12:23:47 AM  File "/config/custom_components/reolink_dev/config_flow.py", line 68, in async_step_user
today at 12:23:47 AM    self.info = await self.async_validate_input(self.hass, user_input)
today at 12:23:47 AM  File "/config/custom_components/reolink_dev/config_flow.py", line 136, in async_validate_input
today at 12:23:47 AM    if not await self.base.connect_api():
today at 12:23:47 AM  File "/config/custom_components/reolink_dev/base.py", line 200, in connect_api
today at 12:23:47 AM    if not await self._api.get_settings():
today at 12:23:47 AM  File "/config/.local/lib/python3.9/site-packages/reolink/camera_api.py", line 420, in get_settings
today at 12:23:47 AM    response = await self.send(body)
today at 12:23:47 AM  File "/config/.local/lib/python3.9/site-packages/reolink/camera_api.py", line 1127, in send
today at 12:23:47 AM    if not await self.login():
today at 12:23:47 AM  File "/config/.local/lib/python3.9/site-packages/reolink/camera_api.py", line 698, in login
today at 12:23:47 AM    response = await self.send(body, param)
today at 12:23:47 AM  File "/config/.local/lib/python3.9/site-packages/reolink/camera_api.py", line 1158, in send
today at 12:23:47 AM    async with self._aiohttp_session.post(
today at 12:23:47 AM  File "/usr/lib/python3.9/site-packages/aiohttp/client.py", line 1117, in __aenter__
today at 12:23:47 AM    self._resp = await self._coro
today at 12:23:47 AM  File "/usr/lib/python3.9/site-packages/aiohttp/client.py", line 520, in _request
today at 12:23:47 AM    conn = await self._connector.connect(
today at 12:23:47 AM  File "/usr/lib/python3.9/site-packages/aiohttp/connector.py", line 535, in connect
today at 12:23:47 AM    proto = await self._create_connection(req, traces, timeout)
today at 12:23:47 AM  File "/usr/lib/python3.9/site-packages/aiohttp/connector.py", line 892, in _create_connection
today at 12:23:47 AM    _, proto = await self._create_direct_connection(req, traces, timeout)
today at 12:23:47 AM  File "/usr/lib/python3.9/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
today at 12:23:47 AM    raise last_exc
today at 12:23:47 AM  File "/usr/lib/python3.9/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
today at 12:23:47 AM    transp, proto = await self._wrap_create_connection(
today at 12:23:47 AM  File "/usr/lib/python3.9/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
today at 12:23:47 AM    raise client_error(req.connection_key, exc) from exc
today at 12:23:47 AMaiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.0.36:443 ssl:default [Connect call failed ('192.168.0.36', 443)]
```

**Comment by cpainchaud** [comment]
can you access your camera when browsing https://192.168.0.36 ?
Can you also configure more precise debugging like mentioned there https://github.com/fwestenberg/reolink_dev/blob/master/TSHOOT.md ?

**Comment by cpainchaud** [comment]
also can you show what you configured for the camera (hotname, port, use_ssl ... etc)

**Comment by kavemang** [comment]
> can you access your camera when browsing https://192.168.0.36 ? Can you also configure more precise debugging like mentioned there https://github.com/fwestenberg/reolink_dev/blob/master/TSHOOT.md ?

yes I can, I probably should have mentioned im consuming the feed for all three cameras with multiple sets of 3rd party software, nonetheless one wifi and one POE cam have this issue. I've tried ports 443, 80 and 1953, ive tried with SSL on and SSL off

**Comment by MiAutomations** [comment]
I'm also having this issue as mentioned in the #406 

Please let me know what You need from the my side  once I have several other reolink cameras models working well without this issue  wi-fi also 

Thank you and best regards

**Comment by xannor** [comment]
Have you tried using just http and not https? Unless you do not trust your network, or are exposing the cameras directly to the internet, adding ssl security is increasing the load on the camera hardware, with very little gain. These devices are probably pushing their processors hard enough with 4k and semi-ai detection, that adding in encryption is probably going to cause things to fail randomly and periodically. Try disabling https and using port 80 and see if it works better.

**Comment by qwik3r** [comment]
I can't seem to login either, but looking at the Reolink Docs it says that the E1 Pro doesn't have a web interface, so I guess that means I can't add the E1 Pro to HA via this integration?

**Comment by Wlada** [comment]
I also have E1 Pro and can't connect.
HTTP://IP:8000

user admin and password

all provided information is ok, but I can't log in.

**Comment by rickbeec** [comment]
Banged at this for an hour. Create a new user of type User. Not and Administrator. I would be great if the documentation had some details for how to get past the first screen. Once you have added your camera, go and enable the substream entity as this seems to overcome the troubling lack of H.265 support in HA.

**Comment by rickbeec** [comment]
Update. Sorry, not solved, it was random. Now I get: 

_Error from stream worker: Error opening stream (ERRORTYPE_104, Connection reset by peer) rtmp://192.168.1.93:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=user12&password=*****
Error from stream worker: Error opening stream (EOF, End of file) rtmp://192.168.1.93:1935/bcs/channel0_main.bcs?channel=0&stream=0&user=user12&password=*****_
