### ISSUE TITLE
Motion sensors and switches not working - Reolink RLC-822A

### ISSUE THREAD

**Issue by rjkrom** [fwestenberg/reolink_dev#313]
Hi all. I still have issues with my Reolink integration.
After installing the latest version of Reolink_dev (v0.26) and restarting home assistant, only the stream is working. None of the switches and binary sensors for motion are are working.

Any idea what the problem could be? 

This is my log:

              "channel" : 0,
               "table" : {
                  "AI_PEOPLE" : {
                     "table" : {
                        "maxLen" : 168,
                        "minLen" : 168
                     }
                  },
                  "AI_VEHICLE" : {
                     "table" : {
                        "maxLen" : 168,
                        "minLen" : 168
                     }
                  },
                  "MD" : {
                     "table" : {
                        "maxLen" : 168,
                        "minLen" : 168
                     }
                  }
               }
            }
         }
      },
      "value" : {
         "Push" : {
            "enable" : 0,
            "schedule" : {
               "channel" : 0,
               "table" : {
                  "AI_PEOPLE" : "111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111",
                  "AI_VEHICLE" : "111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111",
                  "MD" : "111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
               }
            }
         }
      }
   },
   {
      "cmd" : "GetPush",
      "code" : 0,
      "initial" : {
         "Push" : {
            "schedule" : {
               "enable" : 1,
               "table" : "111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
            }
         }
      },
      "range" : {
         "Push" : {
            "schedule" : {
               "enable" : "boolean",
               "table" : {
                  "maxLen" : 168,
                  "minLen" : 168
               }
            }
         }
      },
      "value" : {
         "Push" : {
            "schedule" : {
               "enable" : 0,
               "table" : "111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
            }
         }
      }
   }
]

2021-10-15 15:11:48 DEBUG (MainThread) [custom_components.reolink_dev] Finished fetching reolink data in 0.140 seconds (success: True)
2021-10-15 15:11:48 DEBUG (MainThread) [reolink.camera_api] Sending command: Search to: 192.168.1.251 with body: [{'cmd': 'Search', 'action': 0, 'param': {'Search': {'channel': 0, 'onlyStatus': 1, 'streamType': 'sub', 'StartTime': {'year': 2021, 'mon': 8, 'day': 1, 'hour': 0, 'min': 0, 'sec': 0}, 'EndTime': {'year': 2021, 'mon': 10, 'day': 15, 'hour': 15, 'min': 11, 'sec': 48}}}}]
2021-10-15 15:11:48 DEBUG (MainThread) [reolink.camera_api] send() HTTP Request params ={'cmd': 'Search', 'token': 'b3b4e568add19c5'}
2021-10-15 15:11:48 DEBUG (MainThread) [reolink.camera_api] send() HTTP Request body =[{'cmd': 'Search', 'action': 0, 'param': {'Search': {'channel': 0, 'onlyStatus': 1, 'streamType': 'sub', 'StartTime': {'year': 2021, 'mon': 8, 'day': 1, 'hour': 0, 'min': 0, 'sec': 0}, 'EndTime': {'year': 2021, 'mon': 10, 'day': 15, 'hour': 15, 'min': 11, 'sec': 48}}}}]
2021-10-15 15:11:48 DEBUG (MainThread) [reolink.camera_api] send() HTTP Response status=200
2021-10-15 15:11:48 DEBUG (MainThread) [reolink.camera_api.data] send() HTTP Response data: [
   {
      "cmd" : "Search",
      "code" : 0,
      "value" : {
         "SearchResult" : {
            "channel" : 0
         }
      }
   }
]

2021-10-15 15:11:48 DEBUG (MainThread) [reolink.camera_api] Response from 192.168.1.251: [{'cmd': 'Search', 'code': 0, 'value': {'SearchResult': {'channel': 0}}}]
2021-10-15 15:11:48 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/reolink_dev/sensor.py", line 98, in _update_event_range
    search, _ = await self._base.send_search(start, end, True)
  File "/config/custom_components/reolink_dev/base.py", line 242, in send_search
    return await self._api.send_search(start, end, only_status)
  File "/usr/local/lib/python3.9/site-packages/reolink/camera_api.py", line 993, in send_search
    return search_result["Status"], None
KeyError: 'Status'

Environment:
 - Home Assistant version: 2021.10.4
 - Reolink camera model: RLC-822A
 - Camera firmware number: v3.0.0.177_21012107

Thanks in advance!

**Comment by cpainchaud** [comment]
Make sure you have setup an internal URL and don't use DNS names but IP address. I see no log about we webhooks here. Webhooks are responsible of updating motion sensors

**Comment by rjkrom** [comment]
Thanks for the suggestion.
When setting up de integration I use an IP address.
And in my config file I have setup an internal address being an IP address.

Is there another place where I should check?

**Comment by rjkrom** [comment]
The log keeps containing this message:
2021-10-17 16:29:15 DEBUG (MainThread) [reolink.camera_api.data] send() HTTP Response data scrapped because it's too large.

Any thoughts on this one? Many thanks in advance!

**Comment by cpainchaud** [comment]
make sure you are using HTTP (and not HTTPS) for HA UI, Reolink doesn't support HTTPS webhooks.

**Comment by pod31** [comment]
Hey, the sensors are now updated (I change my SSL configuration for that)
But, the detection sensors seems to stay on "Detected" state longer than i have on the android app ...
"Push notification" button don't work.

See logs (i have only replace the token value)
[reolink-pod31.log](https://github.com/fwestenberg/reolink_dev/files/7475057/reolink-pod31.log)

**Comment by rjkrom** [comment]
> Hey, the sensors are now updated (I change my SSL configuration for that) But, the detection sensors seems to stay on "Detected" state longer than i have on the android app ... "Push notification" button don't work.
> 
> See logs (i have only replace the token value) [reolink-pod31.log](https://github.com/fwestenberg/reolink_dev/files/7475057/reolink-pod31.log)

Could you please tell me what you have changed in your SSL configuration?

**Comment by pod31** [comment]
In fact, I were in SSL in local network (with certificate in configuration.yaml)
I knew it was a problem for Reolink integration.
I have done the SSL configuration outside the local network with Nginx, and in http in local network.

**Comment by rjkrom** [comment]
All switches and sensors are working now with latest camera firmware and latest custom component version. I did need to delete and reinstall custom component and had to reboot the host to make it happen.

thanks for the support and developing this component!
