### ISSUE TITLE
C1 Pro installation error

### ISSUE THREAD

**Issue by Tonny56** [fwestenberg/reolink_dev#398]
I tried to integrate my C1pro camera with v.45 (I used HACS), but I get an error (installation failed).
I use Home Assistant version : core-2021.11.5 , supervisor-2021.10.8 on RP4.
This is the error log:
Logger: homeassistant.config_entries
Source: helpers/network.py:116
First occurred: 20:41:13 (1 occurrences)
Last logged: 20:41:13

Error setting up entry overkapping for reolink_dev
Traceback (most recent call last):
  File "/config/custom_components/reolink_dev/__init__.py", line 79, in async_setup_entry
    push = hass.data[DOMAIN][base.push_manager]
KeyError: 'push_manager-B0411DD68D54'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/reolink_dev/__init__.py", line 88, in async_setup_entry
    await push.subscribe(base.event_id)
  File "/config/custom_components/reolink_dev/base.py", line 335, in subscribe
    get_url(self._hass, prefer_external=False),
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 116, in get_url
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError

**Comment by pannal** [comment]
README.

![image](https://user-images.githubusercontent.com/1359593/151166378-077c1027-5431-45f9-872b-bed9f0e6c1ad.png)
