### ISSUE TITLE
KeyError: 'mode' / whiteled

### ISSUE THREAD

**Issue by dennidoubles** [fwestenberg/reolink_dev#412]
I'm experiencing several issues with Reolink, but cams do work. In the Reolink app, but also in HA.
But my log is full of errors. One of them is this one:

Logger: reolink.camera_api
Source: /usr/local/lib/python3.9/site-packages/reolink/camera_api.py:799
First occurred: 12:46:53 (73 occurrences)
Last logged: 13:58:04

Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/reolink/camera_api.py", line 747, in map_json_response self._whiteled_mode = data["value"]["WhiteLed"]["mode"] KeyError: 'mode'

Running HA 2021.12.4, OS 7.0
Reolink integration v0.46

**Comment by cpainchaud** [comment]
Hi,

 Please provide camera model & firmware. Also provide the output of :
 curl -k  "https://192.168.0.47/cgi-bin/api.cgi?cmd=GetAbility&user=admin&password=PASSWORD&channel=0" 
 and
 curl -k  "https://192.168.0.47/cgi-bin/api.cgi?cmd=GetWhiteLed&user=admin&password=PASSWORD&channel=0"

**Comment by dennidoubles** [comment]
Thank you for your follow up. I took the urls, replaced IP address and Password.


The first given url gives the following output:

[ { "cmd" : "GetAbility", "code" : 1, "error" : { "detail" : "invalid user", "rspCode" : -27 } } ]


The second given url gives me the following output:

[ { "cmd" : "GetWhiteLed", "code" : 1, "error" : { "detail" : "check err", "rspCode" : -3 } } ]


Comment: I can't place the error "invalid user" , I use just admin and my own password.

I also can't relate all the errors to a specific camera, so here are all of them:

Camera model: All RLC-510A camera's (3x, outside)
Firmware: v3.0.0.177_21012102

Camera model: C1 Pro (inside)
Firmware: v2.0.0.448_19061405

Camera model: C1 Pro (inside)
Firmware: v2.0.0.1441_19032105

Camera model: RLC-520 (inside)
Firmware: v2.0.0.647_20031413

**Comment by cpainchaud** [comment]
Please upgrade all your cameras firmware (510A and 520 models) (they are all outdated based on https://reolink.com/download-center/) and then restart Home-Asssitant.

Concerning C1 model, I can't even find it on Reolink's website

**Comment by dennidoubles** [comment]
Ehm, allright. I'll do that first and come back with feedback.

C1 Pro isn't hard to find, but it is outdated. But that shouldn't be the problem of an error in Home Assistant integration, right?
https://reolink.com/product/c1-pro/

You'll be redirected to the E1, but there it is.

**Comment by dennidoubles** [comment]
Hi there.

Meanwhile...Updated all camera's, but error still exists. 

```
Error:
Logger: reolink.camera_api
Source: /usr/local/lib/python3.9/site-packages/reolink/camera_api.py:799
First occurred: 13:09:21 (144 occurrences)
Last logged: 15:31:25

Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/reolink/camera_api.py", line 747, in map_json_response self._whiteled_mode = data["value"]["WhiteLed"]["mode"] KeyError: 'mode'
```

Camera model: All RLC-510A camera's (3x, outside)
Firmware: v3.0.0.494_21073002

Camera model: C1 Pro (inside)
Firmware: v2.0.0.1288_18020705 (checked with Reolink Support, latest firmware before EOL)

Camera model: RLC-520 (inside)
Firnmware: v3.0.0.136_20121112


Output of "https://192.168.0.47/cgi-bin/api.cgi?cmd=GetAbility&user=admin&password=PASSWORD&channel=0"

`[ { "cmd" : "GetAbility", "code" : 1, "error" : { "detail" : "invalid user", "rspCode" : -27 } } ]`

Output of "https://192.168.0.47/cgi-bin/api.cgi?cmd=GetWhiteLed&user=admin&password=PASSWORD&channel=0"

`[ { "cmd" : "GetWhiteLed", "code" : 1, "error" : { "detail" : "check err", "rspCode" : -3 } } ]`

**Comment by Wetalya** [comment]
Hi!
+1 error

```
2022-01-18 23:15:02 ERROR (MainThread) [reolink.camera_api] Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/reolink/camera_api.py", line 747, in map_json_response
self._whiteled_mode = data["value"]["WhiteLed"]["mode"]
KeyError: 'mode'
2022-01-18 23:15:02 ERROR (MainThread) [custom_components.reolink_dev.base] Host 192.168.0.16 subscription failed to its webhook, base object state will be set to NotAvailable
2022-01-18 23:15:02 ERROR (MainThread) [custom_components.reolink_dev.base] Host 192.168.0.16 error renewing the Reolink subscription
2022-01-18 23:15:02 ERROR (MainThread) [reolink.camera_api] Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/reolink/camera_api.py", line 747, in map_json_response
self._whiteled_mode = data["value"]["WhiteLed"]["mode"]
KeyError: 'mode'
2022-01-18 23:16:02 ERROR (MainThread) [custom_components.reolink_dev.base] Host 192.168.0.16 error renewing the Reolink subscription
2022-01-18 23:16:02 ERROR (MainThread) [reolink.camera_api] Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/reolink/camera_api.py", line 747, in map_json_response
self._whiteled_mode = data["value"]["WhiteLed"]["mode"]
KeyError: 'mode'
```

NVR:
> Model - RLN8-410
> Build No. - build 2103125
> Hardware No. - N2MB02
> Config Version - v3.0.0.0
> Firmware Version - v3.0.0.123_21031205

Home Assistant 2021.12.10

**Comment by danlsgiga** [comment]
Same here using the RLN8-410 NVR.
