### ISSUE TITLE
Errors Stream!=ext

### ISSUE THREAD

**Issue by Wetalya** [fwestenberg/reolink_dev#429]
![image](https://user-images.githubusercontent.com/20833318/150010802-f2bdaf61-4adc-4c99-b1e8-783984097d2f.png)
`2022-01-18 23:05:54 ERROR (MainThread) [reolink.camera_api] Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/reolink/camera_api.py", line 747, in map_json_response
self._whiteled_mode = data["value"]["WhiteLed"]["mode"]
KeyError: 'mode'
2022-01-18 23:05:54 ERROR (MainThread) [custom_components.reolink_dev.base] Host 192.168.0.16 subscription failed to its webhook, base object state will be set to NotAvailable
2022-01-18 23:05:54 ERROR (MainThread) [custom_components.reolink_dev.base] Host 192.168.0.16 error renewing the Reolink subscription
2022-01-18 23:05:55 ERROR (MainThread) [reolink.camera_api] Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/reolink/camera_api.py", line 747, in map_json_response
self._whiteled_mode = data["value"]["WhiteLed"]["mode"]
KeyError: 'mode'
2022-01-18 23:05:55 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session
2022-01-18 23:05:55 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connector
2022-01-18 23:06:12 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/reolink_dev/__init__.py", line 125, in update_listener
base.enable_https(entry.options[CONF_USE_HTTPS])
KeyError: 'use_https'
2022-01-18 23:06:18 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtmp://192.168.0.16:1935/bcs/channel2_main.bcs?channel=2&stream=0&user=admin&password=Vetall11
2022-01-18 23:06:20 ERROR (MainThread) [frontend.js.latest.202112291] http://192.168.0.22:8123/frontend_latest/93104ce0.js:8:3340 Uncaught TypeError: Cannot read properties of null (reading 'removeAttribute')
2022-01-18 23:06:55 ERROR (MainThread) [custom_components.reolink_dev.base] Host 192.168.0.16 error renewing the Reolink subscription
2022-01-18 23:06:55 ERROR (MainThread) [reolink.camera_api] Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/reolink/camera_api.py", line 747, in map_json_response
self._whiteled_mode = data["value"]["WhiteLed"]["mode"]
KeyError: 'mode'
2022-01-18 23:07:55 ERROR (MainThread) [custom_components.reolink_dev.base] Host 192.168.0.16 error renewing the Reolink subscription
2022-01-18 23:07:55 ERROR (MainThread) [reolink.camera_api] Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/reolink/camera_api.py", line 747, in map_json_response
self._whiteled_mode = data["value"]["WhiteLed"]["mode"]
KeyError: 'mode'`

![image](https://user-images.githubusercontent.com/20833318/150010935-be584d71-201a-4095-80d1-99312aded04d.png)

NVR:
> Model - RLN8-410
> Build No. - build 2103125
> Hardware No. - N2MB02
> Config Version - v3.0.0.0
> Firmware Version - v3.0.0.123_21031205

Home Assistant 2021.12.10

**Comment by Wetalya** [comment]
Stream=ext  --->   video starts playing
but the error remains:
`2022-01-18 23:22:14 ERROR (MainThread) [reolink.camera_api] Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/reolink/camera_api.py", line 747, in map_json_response
self._whiteled_mode = data["value"]["WhiteLed"]["mode"]
KeyError: 'mode'
2022-01-18 23:22:14 ERROR (MainThread) [custom_components.reolink_dev.base] Host 192.168.0.16 subscription failed to its webhook, base object state will be set to NotAvailable
2022-01-18 23:22:14 ERROR (MainThread) [custom_components.reolink_dev.base] Host 192.168.0.16 error renewing the Reolink subscription
2022-01-18 23:22:14 ERROR (MainThread) [reolink.camera_api] Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/reolink/camera_api.py", line 747, in map_json_response
self._whiteled_mode = data["value"]["WhiteLed"]["mode"]
KeyError: 'mode'
2022-01-18 23:23:14 ERROR (MainThread) [custom_components.reolink_dev.base] Host 192.168.0.16 error renewing the Reolink subscription
2022-01-18 23:23:14 ERROR (MainThread) [reolink.camera_api] Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/reolink/camera_api.py", line 747, in map_json_response
self._whiteled_mode = data["value"]["WhiteLed"]["mode"]
KeyError: 'mode'`
