### ISSUE TITLE
Error setting up entry Camera for reolink_dev

### ISSUE THREAD

**Issue by Wetalya** [fwestenberg/reolink_dev#436]
Home Assistant version 2021.12.10
NVR(RLK8-810B4-A):
> Model - RLN8-410
> Build No. - build 2103125
> Hardware No. - N2MB02
> Config Version - v3.0.0.0
> Firmware Version - v3.0.0.123_21031205

after turning off the explosion and turning it back on, I got an error for all cameras:

```
Эта ошибка возникла в кастомной интеграции.

Logger: homeassistant.config_entries
Source: custom_components/reolink_dev/base.py:207
Integration: Reolink IP camera (documentation, issues)
First occurred: 00:44:38 (2 occurrences)
Last logged: 00:44:38

Error setting up entry Camera1 for reolink_dev
Error setting up entry Camera2 for reolink_dev
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.0.16', 80)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/reolink_dev/__init__.py", line 73, in async_setup_entry
    if not await base.connect_api():
  File "/config/custom_components/reolink_dev/base.py", line 207, in connect_api
    if not await self._api.get_settings():
  File "/usr/local/lib/python3.9/site-packages/reolink/camera_api.py", line 485, in get_settings
    response = await self.send(body)
  File "/usr/local/lib/python3.9/site-packages/reolink/camera_api.py", line 1576, in send
    if not await self.login():
  File "/usr/local/lib/python3.9/site-packages/reolink/camera_api.py", line 828, in login
    response = await self.send(body, param)
  File "/usr/local/lib/python3.9/site-packages/reolink/camera_api.py", line 1610, in send
    async with self._aiohttp_session.post(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.0.16:80 ssl:default [Connect call failed ('192.168.0.16', 80)]

```

**Comment by cpainchaud** [comment]
Hi,

 I don't know what to tell you : it's blaming the OS/network not being able to connect. Are you sure about the IP and port?

**Comment by Wetalya** [comment]
Hi,
absolutely absolutely sure. So I recreated the integration and everything worked fine with the same data

![image](https://user-images.githubusercontent.com/20833318/151219869-aaeccae1-77ef-4f9f-8237-3035d5996417.png)
![image](https://user-images.githubusercontent.com/20833318/151220115-4ddcaf62-7c54-4943-8b40-72fd8fc061b6.png)
![image](https://user-images.githubusercontent.com/20833318/151220178-bc5cf525-9e85-4860-9bc1-e9b727307882.png)

**Comment by MikOsle** [comment]
I'm getting this error too but with at lille different traceback. Recreating the integration also works but as soon I restart Home Assistant the error reoccur. 

"
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/reolink_dev/base.py:214
Integration: Reolink IP camera (documentation, issues)
First occurred: 15:51:01 (2 occurrences)
Last logged: 15:51:01

Error setting up entry Bag hus for reolink_dev
Error setting up entry Indgang for reolink_dev
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 327, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/reolink_dev/__init__.py", line 75, in async_setup_entry
    if not await base.connect_api():
  File "/config/custom_components/reolink_dev/base.py", line 214, in connect_api
    if not await self._api.get_settings():
  File "/usr/local/lib/python3.9/site-packages/reolink/camera_api.py", line 489, in get_settings
    response = await self.send(body)
  File "/usr/local/lib/python3.9/site-packages/reolink/camera_api.py", line 1644, in send
    if not await self.login():
  File "/usr/local/lib/python3.9/site-packages/reolink/camera_api.py", line 838, in login
    response = await self.send(body, param)
  File "/usr/local/lib/python3.9/site-packages/reolink/camera_api.py", line 1685, in send
    async with self._aiohttp_session.post(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 913, in start
    self._continue = None
  File "/usr/local/lib/python3.9/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
"
