### ISSUE TITLE
RLC-411S not adding in HA

### ISSUE THREAD

**Issue by sscheuri** [fwestenberg/reolink_dev#456]
Getting "Unexpected error" when attempting to add RLC-411S camera to HA. Using latest version of reolink_dev. Integration working for RLC-410S camera on same subnet. 

Attempted to reboot RLC-411S camera and was not successful in fixing issue. Reboot via app, and by pulling ethernet cable/PoE power.

**Comment by nexustp** [comment]
same issue with RLC-820A

**Comment by rizz360** [comment]
I have the same issue with RLC-410W.

**Comment by drlauridsen** [comment]
Same here with RLC520A.

Had success a couple of times after deleting both cam integration AND the HACS Reolink integration, restarting, and then reinstall of both HACS Reolink integration and camera, but now it won't add the camera no matter what I do. Login to cam with same credentials works fine..

`Denne fejl stammer fra en brugerdefineret integration.

Logger: homeassistant.config_entries
Source: custom_components/reolink_dev/base.py:214
Integration: Reolink IP camera (documentation, issues)
First occurred: 17.50.55 (1 occurrences)
Last logged: 17.50.55

Error setting up entry CAM1 for reolink_dev
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/reolink_dev/__init__.py", line 75, in async_setup_entry
    if not await base.connect_api():
  File "/config/custom_components/reolink_dev/base.py", line 214, in connect_api
    if not await self._api.get_settings():
  File "/usr/local/lib/python3.9/site-packages/reolink/camera_api.py", line 489, in get_settings
    response = await self.send(body)
  File "/usr/local/lib/python3.9/site-packages/reolink/camera_api.py", line 1710, in send
    raise CredentialsInvalidError()
reolink.exceptions.CredentialsInvalidError`
