### ISSUE TITLE
API returned HTTP status ERROR code 502/Bad Gateway

### ISSUE THREAD

**Issue by galex80** [fwestenberg/reolink_dev#472]
**Describe the bug**
Since the latest update, i recognized this error in my logs:

Logger: custom_components.reolink_dev
Source: custom_components/reolink_dev/base.py:255
Integration: Reolink IP camera ([documentation](https://github.com/fwestenberg/reolink_dev), [issues](https://github.com/fwestenberg/reolink_dev/issues))
First occurred: March 16, 2022, 5:35:23 PM (3 occurrences)
Last logged: 6:34:09 AM

Unexpected error fetching reolink.Hauseingang data: API returned HTTP status ERROR code 502/Bad Gateway
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/reolink_dev/__init__.py", line 98, in async_update_data
    await base.update_states()
  File "/config/custom_components/reolink_dev/base.py", line 255, in update_states
    await self._api.get_states()
  File "/usr/local/lib/python3.9/site-packages/reolink/camera_api.py", line 460, in get_states
    response = await self.send(body)
  File "/usr/local/lib/python3.9/site-packages/reolink/camera_api.py", line 1714, in send
    raise ApiError(
reolink.exceptions.ApiError: API returned HTTP status ERROR code 502/Bad Gateway
**To Reproduce**
Unclear, how to reproduce this issue

**Expected behavior**

**Screenshots**

**Environment:**
Please provide useful information about your environment, like:
 - Home Assistant version
Version | core-2022.3.5
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.9
Operating System Family | Linux
Operating System Version | 5.10.92-v8
CPU Architecture | aarch64

Host Operating System | Home Assistant OS 7.5
Update Channel | stable
Supervisor Version | supervisor-2022.03.4

 - Reolink camera model : RLC-520
 - Camera firmware number: v3.0.0.136_20121112

**Comment by rplevka** [comment]
:+1:

**Comment by Wibias** [comment]
Yea please fix this or at least dont let it appear. Its spamming my log and its coming over homeassistant so I cant even suppress the log. @fwestenberg

**Comment by Wibias** [comment]
There is a firmware update. Maybe that helps.

https://reolink.com/download-center/?firmware-product=e1-zoom

**Comment by stalakerob** [comment]
I also got this error and several others. I did 2 things that made most of those disappear, incl. the 502/bad gateway error:
- I did a factory reset of my camera (RLC-811A)
- I had a generic camera configuration for a cam that I removed from the network. I deleted this cam from the generic camera integration. 
I'm still getting this warning sporadically, sometimes many in a row:
- WARNING (MainThread) [reolink.camera_api] Host: 192.168.1.205: Failed to get results for Search, JSON data was was empty?
and sometimes this error:
- ERROR (MainThread) [custom_components.reolink_dev] Timeout fetching reolink.GartenCam.motion_states data

**Comment by Wibias** [comment]
Removing the camera from the generic camera configuration seems to fix it for me.

**Comment by arigit** [comment]
@Wibias  what generic camera configuration are you referring to? can you elaborate? is this something you had in configuration.yaml, or another integration you had before? I don't seem to have either any reference to this cam in yaml nor any other camera integration
I see this error as well. Half a dozen times per hour or so

**Comment by stalakerob** [comment]
@arigit 
Generic Camera: [https://www.home-assistant.io/integrations/generic/](url)
This worked for me for a while but then the error came back and some others too. So I went away from this component and switched to WebRTC and REST for the alarms. See here [https://community.home-assistant.io/t/reolink-nvr-to-home-assistant-issue/430491](url)
