### ISSUE TITLE
Add Camera "unexpect failture"

### ISSUE THREAD

**Issue by andybali** [fwestenberg/reolink_dev#475]
**Describe the bug**
Add Camera "unexpect failture" on RLC510A. Other (RLC-510WA) works fine

**To Reproduce**
`Logger: custom_components.reolink_dev.config_flow
Source: custom_components/reolink_dev/base.py:219
Integration: Reolink IP camera ([documentation](https://github.com/fwestenberg/reolink_dev), [issues](https://github.com/fwestenberg/reolink_dev/issues))
First occurred: 21. März 2022, 22:04:44 (2 occurrences)
Last logged: 07:38:57

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/reolink_dev/config_flow.py", line 70, in async_step_user
    self.info = await self.async_validate_input(self.hass, user_input)
  File "/config/custom_components/reolink_dev/config_flow.py", line 138, in async_validate_input
    if not await self.base.connect_api():
  File "/config/custom_components/reolink_dev/base.py", line 219, in connect_api
    if not await self._api.get_settings():
  File "/usr/local/lib/python3.9/site-packages/reolink/camera_api.py", line 496, in get_settings
    response = await self.send(body)
  File "/usr/local/lib/python3.9/site-packages/reolink/camera_api.py", line 1721, in send
    raise CredentialsInvalidError()
reolink.exceptions.CredentialsInvalidError`

**Environment:**
Please provide useful information about your environment, like:
 - Home Assistant version 	core-2022.3.5
 - Reolink camera model: RLC-510A
 - Camera firmware number IPC_523128M5MP.764_21121702.RLC-510A.OV05A10.5MP.REOLINK.pak

**Comment by LeidenSpain** [comment]
Hi, I have the same problem, but with the RLC-510WA
`Logger: custom_components.reolink_dev.config_flow
Source: custom_components/reolink_dev/base.py:219
Integration: Reolink IP camera ([documentation](https://github.com/fwestenberg/reolink_dev), [issues](https://github.com/fwestenberg/reolink_dev/issues))
First occurred: 11:08:01 (1 occurrences)
Last logged: 11:08:01

Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.8.205', 443)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/reolink_dev/config_flow.py", line 70, in async_step_user
    self.info = await self.async_validate_input(self.hass, user_input)
  File "/config/custom_components/reolink_dev/config_flow.py", line 138, in async_validate_input
    if not await self.base.connect_api():
  File "/config/custom_components/reolink_dev/base.py", line 219, in connect_api
    if not await self._api.get_settings():
  File "/usr/local/lib/python3.9/site-packages/reolink/camera_api.py", line 496, in get_settings
    response = await self.send(body)
  File "/usr/local/lib/python3.9/site-packages/reolink/camera_api.py", line 1652, in send
    if not await self.login():
  File "/usr/local/lib/python3.9/site-packages/reolink/camera_api.py", line 845, in login
    response = await self.send(body, param)
  File "/usr/local/lib/python3.9/site-packages/reolink/camera_api.py", line 1696, in send
    async with session.post(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.8.205:443 ssl:default [Connect call failed ('192.168.8.205', 443)]`

Environment:
Home Assistant version core-2022.3.8

Model RLC-510WA
Build No. build 21121712
Hardware No. IPC_523128M5MP
Config Version v3.1.0.0
Firmware Version v3.1.0.764_21121712
Details IPC_523128M5MPS10E1W31100000001

Reolink IP camera 0.51
