### ISSUE TITLE
RLC-510WA and FW v3.1.0.x

### ISSUE THREAD

**Issue by Swiftrail84** [fwestenberg/reolink_dev#486]
Having trouble since update v3.1.0.764_21121712. My Card in HASS told me:

„ This entity is currently unavailable and is widowed for a removed, changed, or disrupted integration or device.

 If the entity is no longer used, you can clean it up by removing it.“.

There is no image since the update.

![E79F1C4D-3A67-48A7-A400-CDD8019BB17B](https://user-images.githubusercontent.com/68839593/163571155-9491d8e1-1578-4263-b084-9e503708e9db.jpeg)

**Comment by garry0garry** [comment]
reolink_dev v0.53
Reolink RLC-511WA fw v3.1.0.956_22041509
Reolink RLC-520A fw v3.1.0.951_22041566
***
Logger: reolink.camera_api
Source: /usr/local/lib/python3.9/site-packages/reolink/camera_api.py:1605
First occurred: 21:30:50 (79 occurrences)
Last logged: 22:25:52

Host: 192.168.50.62: Failed to get results for Search, JSON data was was empty?
Host: 192.168.50.140: Failed to get results for Search, JSON data was was empty?
Host: 192.168.50.177: Failed to get results for Search, JSON data was was empty?
Host: 192.168.50.162: Failed to get results for Search, JSON data was was empty?
Host: 192.168.50.63: Failed to get results for Search, JSON data was was empty?
***
Logger: custom_components.reolink_dev.base
Source: custom_components/reolink_dev/base.py:416
Integration: Reolink IP camera (documentation, issues)
First occurred: 21:30:45 (18 occurrences)
Last logged: 22:21:25

Host 192.168.50.62 error renewing the Reolink subscription
Host 192.168.50.27 error renewing the Reolink subscription
Host 192.168.50.177 error renewing the Reolink subscription
Host 192.168.50.162 error renewing the Reolink subscription
Host 192.168.50.63 error renewing the Reolink subscription
***
Logger: homeassistant
Source: custom_components/reolink_dev/base.py:526
Integration: Reolink IP camera (documentation, issues)
First occurred: 21:31:04 (2 occurrences)
Last logged: 21:56:04

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/reolink_dev/sensor.py", line 163, in handle_event
    await self._hass.async_add_job(self._update_event_range)
  File "/config/custom_components/reolink_dev/sensor.py", line 132, in _update_event_range
    end = searchtime_to_datetime(file["EndTime"], start.tzinfo)
  File "/config/custom_components/reolink_dev/base.py", line 526, in searchtime_to_datetime
    return dt.datetime(
ValueError: year 0 is out of range

**Comment by GewoonRoy** [comment]
Got the exact same issue with the same firmware v3.1.0.956
