### ISSUE TITLE
Reolink 811a video feed not working (timeout)

### ISSUE THREAD

**Issue by TASSDevon** [fwestenberg/reolink_dev#496]
**Describe the bug**
When adding a Reolink 811a I get all entities, all seems to work, though for the camera feed itself, I see the thumbnail when I add the camera to an entities card, but when I click on it to see the actual feed I just get a white screen, no video is loading.

**To Reproduce**
Try playing a live video feed, nothing is loading

**Expected behavior**
Video feed should play

**Screenshots**

<img width="414" alt="Screenshot 2022-05-07 at 14 10 16" src="https://user-images.githubusercontent.com/6917072/167253797-e2788194-19ac-42de-9691-97b0c65d3465.png">

**Environment:**
Please provide useful information about your environment, like:
 - Home Assistant version 2022.5.1
 - Reolink camera model 811a
 - Camera firmware number latest

**Comment by theklunky** [comment]
Hi, I'm having the exact same issue with a RLC-820A that I just installed. My RLC-4205MP that it replaced worked properly before that. Diving into the logs produced this.

> 2022-05-09 15:32:33 ERROR (MainThread) [custom_components.reolink_dev.base] Host 10.1.1.22 error renewing the Reolink subscription
2022-05-09 15:32:48 ERROR (stream_worker) [libav.rtmp] Cannot read RTMP handshake response
2022-05-09 15:32:48 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.front] Error from stream worker: Error opening stream (ERRORTYPE_104, Connection reset by peer) rtmp://****:****@ss
2022-05-09 15:33:11 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Front-Right for reolink_dev
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 474, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/config/custom_components/reolink_dev/__init__.py", line 182, in async_unload_entry
    hass.data[DOMAIN].pop(base.push_manager)
KeyError: 'push_manager-ec71dba882f8'
2022-05-09 15:33:29 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Front-Right for reolink_dev
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 474, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/config/custom_components/reolink_dev/__init__.py", line 182, in async_unload_entry
    hass.data[DOMAIN].pop(base.push_manager)
KeyError: 'push_manager-ec71dba882f8'
2022-05-09 15:34:07 ERROR (MainThread) [custom_components.reolink_dev.base] Host 10.1.1.22 subscription failed to its webhook, base object state will be set to NotAvailable
2022-05-09 15:34:07 ERROR (MainThread) [custom_components.reolink_dev.base] Host 10.1.1.22 error renewing the Reolink subscription
2022-05-09 15:34:25 ERROR (stream_worker) [libav.rtmp] Cannot read RTMP handshake response
2022-05-09 15:34:25 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.front] Error from stream worker: Error opening stream (EOF, End of file) rtmp://****:****@ss
2022-05-09 15:34:35 ERROR (stream_worker) [libav.rtmp] Cannot read RTMP handshake response
2022-05-09 15:34:35 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.front] Error from stream worker: Error opening stream (ERRORTYPE_104, Connection reset by peer) rtmp://****:****@ss
2022-05-09 15:34:48 ERROR (stream_worker) [libav.rtmp] Cannot read RTMP handshake response
2022-05-09 15:34:48 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.front] Error from stream worker: Error opening stream (EOF, End of file) rtmp://****:****@ss
2022-05-09 15:34:55 ERROR (stream_worker) [libav.rtmp] Cannot read RTMP handshake response
2022-05-09 15:34:55 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.front] Error from stream worker: Error opening stream (ERRORTYPE_104, Connection reset by peer) rtmp://****:****@ss
2022-05-09 15:35:07 ERROR (MainThread) [custom_components.reolink_dev.base] Host 10.1.1.22 error renewing the Reolink subscription
2022-05-09 15:35:22 ERROR (stream_worker) [libav.rtmp] Cannot read RTMP handshake response
2022-05-09 15:35:22 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.front] Error from stream worker: Error opening stream (EOF, End of file) rtmp://****:****@ss
2022-05-09 15:35:25 ERROR (stream_worker) [libav.rtmp] Cannot read RTMP handshake response
2022-05-09 15:35:25 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.front] Error from stream worker: Error opening stream (ERRORTYPE_104, Connection reset by peer) rtmp://****:****@ss
2022-05-09 15:36:05 ERROR (stream_worker) [libav.rtmp] Cannot read RTMP handshake response

**Environment:**

- HA: 2022.5.3
- Camera: Reolink RLC-820A
- Camera firmware: v3.1.0.956_22041501

**Comment by TASSDevon** [comment]
I got the low res substream working, but only using webrtc and local lan IP. I would really like to be able to access the sub or main stream while "away" as weell. I have a foscam which can do this without problems so it's not a config issue (NAT, routing etc).

**Comment by theklunky** [comment]
> I got the low res substream working, but only using webrtc and local lan IP. I would really like to be able to access the sub or main stream while "away" as weell. I have a foscam which can do this without problems so it's not a config issue (NAT, routing etc).

What steps did you take to get that working? I tried the simple streaming integration as well as the ONVIF integration and neither worked.

**Comment by theklunky** [comment]
Alright, I figured out a way but it involves decreasing the resolution of the camera. If you don't go full 4K, the resolution below (2560x1440) will provide a H264 stream and not H265. This will then display in home assistant properly.

**Comment by TASSDevon** [comment]
Could you explain what you did? Settings etc? Are you using the Reolink integration?

**Comment by reepje123** [comment]
I'm having the same issue with my RLC-811A too.
Apparantly the main stream isn't supported when using RTMP. Source: [Reddit](https://www.reddit.com/r/reolinkcam/comments/m5szcm/rtmp_url_for_rlc810a/gr39h8h/?utm_source=reddit&utm_medium=web2x&context=3).
No matter which protocol or stream I configure, whenever I open the stream (by clicking the card) it always tries to open the RTMP main URL which obviously doesn't work.

**Comment by theklunky** [comment]
> Could you explain what you did? Settings etc? Are you using the Reolink integration?

Within the reolink app, set your stream's resolution to 2560x1440. This will also set your stream to h264. Then, in home assistant's reolink integration, you should be able to add your camera. I could only add it via http.

**Comment by 0dragosh** [comment]
Is there any other way of getting the stream to work without downgrading the resolution?

**Comment by ZachPL** [comment]
I just came across the same problem, I just installed a reolink 811a and my live stream doesn't work with 4k res, im assuming because of h265.

For now I guess i'll just keep full res in the reolink app and using webrtc

rtsp://user:pass@ip:554/h264Preview_01_sub displays fine in a lower res without me having to change the res in the reolink app, not ideal but for my purposes will be fine until someone comes up with another solution hopefully

**Comment by theklunky** [comment]
> Is there any other way of getting the stream to work without downgrading the resolution?

I couldn't find one. I agree, downgrading the resolution is a fix but not a solution. I bought a 4K camera to use it and it pretty frustrating that I can't.

> For now I guess i'll just keep full res in the reolink app and using webrtc

I was unable to get the webrtc integration working in my home assistant instance. I installed it through HACS without errors but it just never showed up when I tried adding it in HA...
