### ISSUE TITLE
Error after upgrade to v0.53  

### ISSUE THREAD

**Issue by KentEkl** [fwestenberg/reolink_dev#499]
Felet härrör från en anpassad integration.

Logger: custom_components.reolink_dev.binary_sensor
Source: custom_components/reolink_dev/binary_sensor.py:126 
Integration: Reolink IP camera (documentation, issues) 
First occurred: 09:01:34 (24 occurrences) 
Last logged: 09:25:34

Traceback (most recent call last): File "/config/custom_components/reolink_dev/binary_sensor.py", line 122, in handle_event await self._base.api.get_all_motion_states() File "/usr/local/lib/python3.9/site-packages/reolink/camera_api.py", line 608, in get_all_motion_states response = await self.send(body) File "/usr/local/lib/python3.9/site-packages/reolink/camera_api.py", line 1696, in send async with session.post( File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__ self._resp = await self._coro File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request conn = await self._connector.connect( File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect proto = await self._create_connection(req, traces, timeout) File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection _, proto = await self._create_direct_connection(req, traces, timeout) File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection transp, proto = await self._wrap_create_connection( File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection return await self._loop.create_connection(*args, **kwargs) # type: ignore[return-value] # noqa File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1081, in create_connection transport, protocol = await self._create_connection_transport( File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1111, in _create_connection_transport await waiter asyncio.exceptions.CancelledError

**Comment by KentEkl** [comment]
ReInstalled V0.52 and now I get a couple of  errors:

Instead of a debug error every minute.

Felet härrör från en anpassad integration. 

Logger: custom_components.reolink_dev
Source: helpers/update_coordinator.py:197 
Integration: Reolink IP camera (documentation, issues) 
First occurred: 17:07:25 (5 occurrences) 
Last logged: 19:37:25

Timeout fetching reolink.Cam1.motion_states data
