### ISSUE TITLE
Integration "Failed to set up" for several versions already

### ISSUE THREAD

**Issue by Barley194** [fwestenberg/reolink_dev#501]
So sometimes when restarting HomeAssistant this integration won't start. In such case another HA restart is needed, and sometimes even one more. Basically as long until it 'clicks' and start properly. 

It's happening for several months now. On various versions. HA and this integration is updated as soon as there is a new update available. 

That's the only error I saw related to this. But maybe there is yet another spot to look in - let me know

![obraz](https://user-images.githubusercontent.com/20290894/167889493-bfdd0cf0-0d30-4750-8055-5f39e9ea163f.png)

`2022-05-11 05:36:37 ERROR (MainThread) [custom_components.reolink_dev] Timeout fetching reolink.Reolink410WFirst.motion_states data
2022-05-11 11:41:07 ERROR (MainThread) [custom_components.reolink_dev] Timeout fetching reolink.Reolink410WFirst.motion_states data
2022-05-11 13:44:32 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration reolink_dev which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-05-11 17:12:06 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration reolink_dev which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant`

**Comment by michalkruczek** [comment]
I have got the same today. After HA restart it works fine but generates error like below:

"Logger: custom_components.reolink_dev
Source: custom_components/reolink_dev/base.py:414
Integration: Reolink IP camera ([documentation](https://github.com/fwestenberg/reolink_dev), [issues](https://github.com/fwestenberg/reolink_dev/issues))
First occurred: 14:40:37 (37 occurrences)
Last logged: 15:16:38

Unexpected error fetching reolink.Popradzka1 data: 'NoneType' object has no attribute 'renewtimer'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 190, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 150, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/reolink_dev/__init__.py", line 97, in async_update_data
    await push.renew()
  File "/config/custom_components/reolink_dev/base.py", line 414, in renew
    if self._sman.renewtimer <= SESSION_RENEW_THRESHOLD:
AttributeError: 'NoneType' object has no attribute 'renewtimer'

**Comment by 0dragosh** [comment]
I have the exact same problem.

**Comment by koburg** [comment]
yes also get this often
