### ISSUE TITLE
Not working in HA 2022.7.0b1

### ISSUE THREAD

**Issue by SmarterHomeLife** [fwestenberg/reolink_dev#525]
The Reolink integration doesn't work after updating to Home Assistant 2022.7.0b0, I assume this is due to the update to Python 3.10.  This is the error from the logs;

Logger: homeassistant.config_entries
Source: custom_components/reolink_dev/base.py:219
Integration: Reolink IP camera ([documentation](https://github.com/fwestenberg/reolink_dev), [issues](https://github.com/fwestenberg/reolink_dev/issues))
First occurred: 5:52:06 am (1 occurrences)
Last logged: 5:52:06 am

Error setting up entry 4 Selway for reolink_dev
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1089, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1119, in _create_connection_transport
    await waiter
  File "/usr/local/lib/python3.10/asyncio/sslproto.py", line 534, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/local/lib/python3.10/asyncio/sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.10/ssl.py", line 975, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/reolink_dev/__init__.py", line 75, in async_setup_entry
    if not await base.connect_api():
  File "/config/custom_components/reolink_dev/base.py", line 219, in connect_api
    if not await self._api.get_settings():
  File "/usr/local/lib/python3.10/site-packages/reolink/camera_api.py", line 496, in get_settings
    response = await self.send(body)
  File "/usr/local/lib/python3.10/site-packages/reolink/camera_api.py", line 1652, in send
    if not await self.login():
  File "/usr/local/lib/python3.10/site-packages/reolink/camera_api.py", line 845, in login
    response = await self.send(body, param)
  File "/usr/local/lib/python3.10/site-packages/reolink/camera_api.py", line 1696, in send
    async with session.post(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 990, in _wrap_create_connection
    raise ClientConnectorSSLError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host 10.0.4.121:443 ssl:default [[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)]

**Comment by martymoose** [comment]
confirmed not working here as well

**Comment by genkizs** [comment]
Not working for me either

**Comment by pdegenhardt** [comment]
Yup just updated HA and Reo Link cameras are all off the air with SSL issue.

**Comment by harishvelli** [comment]
Same issue here.

**Comment by xcomputerman** [comment]
Can also confirm, getting the same error on 2022.7.0 for all my Reolink cameras.

**Comment by cris1410** [comment]
Same here

**Comment by cpainchaud** [comment]
what are your camera's models and firmware version? It seems to complain that your camera is using an old protocol.

**Comment by cpainchaud** [comment]
probably related:
https://github.com/home-assistant/core/issues/74551
https://github.com/home-assistant/core/issues/74558

**Comment by Traseus** [comment]
Same here.
My cams are:
E1 Outdoor with FW v3.0.0.460_21071406
E1 Zoom with FW v3.0.0.716_21112408

**Comment by ckd77** [comment]
> what are your camera's models and firmware version? It seems to complain that your camera is using an old protocol.

1 x E1 Outdoor firmware V3.0.0.748_21120806
2 x E1 Zoom firmware V3.0.0.716_2111408 (up to date)

<img width="935" alt="image" src="https://user-images.githubusercontent.com/37633790/177726059-23b5c4b0-0910-4178-a6ef-c4d6f58c7c13.png">

**Comment by cpainchaud** [comment]
Can you also try command:
openssl s_client -connect <Your camera IP here>:443

and check which version of TLS/SSL is used?

**Comment by ckd77** [comment]
> openssl s_client -connect :443

`# openssl s_client -connect 192.168.10.82:443
CONNECTED(00000003)
Can't use SSL_get_servername
depth=0 C = CN, ST = GD, L = SZ, O = reokink, OU = REOLINK, CN = reolink, emailAddress = service@reo-link.com
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 C = CN, ST = GD, L = SZ, O = reokink, OU = REOLINK, CN = reolink, emailAddress = service@reo-link.com
verify error:num=21:unable to verify the first certificate
verify return:1
depth=0 C = CN, ST = GD, L = SZ, O = reokink, OU = REOLINK, CN = reolink, emailAddress = service@reo-link.com
verify return:1
---
Certificate chain
 0 s:C = CN, ST = GD, L = SZ, O = reokink, OU = REOLINK, CN = reolink, emailAddress = service@reo-link.com
   i:C = CN, ST = GD, L = SZ, O = REOLINK, OU = REOLINK, CN = REOLINK, emailAddress = service@reo-link.com
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIEejCCAmICAQEwDQYJKoZIhvcNAQELBQAwgYIxCzAJBgNVBAYTAkNOMQswCQYD
VQQIDAJHRDELMAkGA1UEBwwCU1oxEDAOBgNVBAoMB1JFT0xJTksxEDAOBgNVBAsM
B1JFT0xJTksxEDAOBgNVBAMMB1JFT0xJTksxIzAhBgkqhkiG9w0BCQEWFHNlcnZp
Y2VAcmVvLWxpbmsuY29tMB4XDTIxMDgyODA3NDA0OVoXDTQxMDgyMzA3NDA0OVow
gYIxCzAJBgNVBAYTAkNOMQswCQYDVQQIDAJHRDELMAkGA1UEBwwCU1oxEDAOBgNV
BAoMB3Jlb2tpbmsxEDAOBgNVBAsMB1JFT0xJTksxEDAOBgNVBAMMB3Jlb2xpbmsx
IzAhBgkqhkiG9w0BCQEWFHNlcnZpY2VAcmVvLWxpbmsuY29tMIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3vvjts+srqbKffNOZCSZVC9WUmzFcknaxTCi
rhayTNyQ3qkkahKVhZti8itaqw4xc0zcNoHQnG9bpvbW68Z9eu0Rrp2pDKYi65mz
I8olDUR0kOF2wSOyK2IiQ6XIXp0sr1Yy+Wx6p42QK2XHzvU6j9x/cA6r0CqAhe9l
35o1G3aRY417DFGa1RxOB6YJkdUk4xMMX26WQRh6AsBd4+sRQIyKbJET80UQIfgs
3jaQOA2uUeR7Ky8JOluPAo0t8N3anGzti+FPKhVC/8kybdyeE3Zg76Z5c+NqhcGY
VfyMWsncY/QWTT4unwetl7Ctw1iBWAbZmQnu+JRBETjg8sg+vwIDAQABMA0GCSqG
SIb3DQEBCwUAA4ICAQBX/OQ6nQ136edC0iIEnEH5eQwaimqwRT0wJUwMjNneiBz2
Wagm1qMQ1Qm1ZtyR2VVWEVo+xgtYzqR+DqlVD6VRKICdGZLFsHQ12fzltZwPpdHG
oIvV7PNXKvEPD42rFX2OuCfJ5EjMnURLwIhAMp35EGUxrSpA2uOjtiG5ewWfOKZF
fGHxpOMo/isQSixhMx8vJUeEUHZ10Qk1XgXsXwlMhvN53TK5JCU/641gPGWMANSn
k49c2O3PPu+M+uZtg0edmokHnZM9J8BDlJULGEe/twQdzuqbsR9ps/JWVE/8kSdG
5GMHfS34aMRm9DyBn0/8rq87M6TagojNFj7AvsfLrPmqrTuUL5eqlJhDZnMjUc46
eqYyecPaHuSRwp5HZqLK3yCuI1/kSCRuf70sUPbJvhDjTk18G9PJ4DgTmTigy+71
Kt6psHS3Go6mn0wLdz3GjdGuALtz/deAzy9+n52/Wdk3EmXeMNNc2GVezPQFaMWY
4uTyNd6gLdGwv4fYIW6wE1HMT/myDDwdxP2AAyq3T+n+Xo9f0pd2/c0ka6toa1Jn
kXB952K7LTTzv/eJE7t6hurfmMb6y5Yis7SWBN9IrYaSMFmjLqTX2zPJmW+KOElI
uN01zNytlIEb8I+Xd3wgrB1A9nvzJ+2Uk/FcC1qTYMR7xORXZXe340jCg7iJTg==
-----END CERTIFICATE-----
subject=C = CN, ST = GD, L = SZ, O = reokink, OU = REOLINK, CN = reolink, emailAddress = service@reo-link.com

issuer=C = CN, ST = GD, L = SZ, O = REOLINK, OU = REOLINK, CN = REOLINK, emailAddress = service@reo-link.com

---
No client certificate CA names sent
---
SSL handshake has read 1474 bytes and written 601 bytes
Verification error: unable to verify the first certificate
---
New, TLSv1.2, Cipher is AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : AES256-GCM-SHA384
    Session-ID: 5A29108A9F705DC883C90CBE59F4CD2F5C08D8221C47D9ECF79FB0E68E1360FA
    Session-ID-ctx:
    Master-Key: EF69F23F8D02690425ECAFF75D25914BC5C83BAF614DCF9C3DFCE0D4AF7AC975D6701AE94F55DF47A037E01CB218246F
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - ce ef 90 50 6c 2a 61 43-c9 1a bf 52 18 b0 94 0a   ...Pl*aC...R....
    0010 - 0a 91 b8 90 c8 77 d8 cb-cd 6c 85 d0 f3 c6 d6 df   .....w...l......
    0020 - d3 b9 24 b1 3a df 72 ed-e7 79 31 f9 28 4d 17 a7   ..$.:.r..y1.(M..
    0030 - 8e 27 22 0c 17 67 fb 36-e2 3b b3 18 4f c1 14 1c   .'"..g.6.;..O...
    0040 - 90 b7 64 2b af c4 44 4e-ef be 06 1e fe a5 10 e1   ..d+..DN........
    0050 - 69 69 f3 70 65 3e 46 b1-99 ec 59 81 c8 8b 3e 1c   ii.pe>F...Y...>.
    0060 - b3 d8 87 8b aa 21 48 64-27 b3 ad 87 ce 9d 1b b6   .....!Hd'.......
    0070 - e2 c0 a6 59 71 6e ff 9b-72 79 4c 84 ca 43 cc 80   ...Yqn..ryL..C..
    0080 - 1d 64 85 de 49 70 8b aa-1b 92 29 8a 22 92 29 01   .d..Ip....).".).
    0090 - 88 81 0d 91 bf b4 49 fb-f5 45 db fa 31 5a d5 e7   ......I..E..1Z..
    00a0 - f0 67 c2 21 f9 6d f5 91-05 70 6d 0b 6c b5 ab 98   .g.!.m...pm.l...

    Start Time: 1657182106
    Timeout   : 7200 (sec)
    Verify return code: 21 (unable to verify the first certificate)
    Extended master secret: no
---
`

**Comment by cpainchaud** [comment]
It's looking good, HA has witched to python 3.10 and restricted some SSL protocols, I don't have the details, it will take time to understand what can be done to override their SSL requirements

**Comment by ckd77** [comment]
Yes, I did a personal backtrack to version 2022.6.7 in order to find my cameras and my mi flora bluetooth modules which no longer work either, as I will soon be going on vacation, I need to have a view of my plants for remote watering and the safety of my home!

**Comment by ckd77** [comment]
I just recently installed a pi4 with home assistant 2022.7 on it, same problem with the SSL layer.

**Comment by cris1410** [comment]
After updating to core 2022.7. four of my 5 cameras stop working.
That is very strange cause all 5 cameras have very similar setup. They only differ in IP adresses.
So I have no idea why 1 of them continue to work and remaining 4 not.

I rolled back to 2022.6. while there will be fix.

**Comment by SmarterHomeLife** [comment]
An option until the issue is resolved with the integration is to use ffmpeg to stream the rtmp feed from your cameras, it won't provide motion sensor outputs or PTZ control but stream video well and allows you to upgrade to 2022.7.

  - platform: ffmpeg
    name: My Camera
    input: 'rtmp://192.168.x.x/bcs/channel0_main.bcs?channel=0&stream=0&user=user&password=password'

**Comment by tagz1979** [comment]
I'm also having this issue after 2022.7.0 had to roll back to 2022.6.7

**Comment by gyorgybekes** [comment]
> I've been watching this issue as I have the same error in an integration I manage. Just cracked the secret code.
> 
> ```
>             context = ssl.create_default_context()
>             context.set_ciphers("DEFAULT")
>             context.check_hostname = False
>             context.verify_mode = ssl.CERT_NONE
> ```

does this solve the issue? where do you add this snippet? Thanks.

**Comment by PeteRager** [comment]
That solved **my** issue. 

https://github.com/PeteRager/lennoxs30/issues/174

Since the errors are the same, this may be the solution also for this integration.   I pass this context into the aiohttp requests using the ssl= parameter.

**Comment by chiefcomm** [comment]
I found that by changing the settings in my camera (RLC-822A) I got things to work via http (only) and adding again into HA.  As my cameras have local access only this isn't a concern for me right now.

![image](https://user-images.githubusercontent.com/45157523/177970199-f3a22745-eec2-4387-851f-60a7949b65ba.png)

**Comment by Tovrin** [comment]
> what are your camera's models and firmware version? It seems to complain that your camera is using an old protocol.

Reolink RLC-520A and on the latest firmware.

**Comment by chimie007** [comment]
similar issue with 2022.7 

Cameras RLC-822A. Log below

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/reolink_dev/base.py:219
Integration: Reolink IP camera (documentation, issues)
First occurred: 19:50:43 (2 occurrences)
Last logged: 19:50:43

Error setting up entry Front for reolink_dev
Error setting up entry Corner for reolink_dev
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1089, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1119, in _create_connection_transport
    await waiter
  File "/usr/local/lib/python3.10/asyncio/sslproto.py", line 534, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/local/lib/python3.10/asyncio/sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.10/ssl.py", line 975, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/reolink_dev/__init__.py", line 75, in async_setup_entry
    if not await base.connect_api():
  File "/config/custom_components/reolink_dev/base.py", line 219, in connect_api
    if not await self._api.get_settings():
  File "/usr/local/lib/python3.10/site-packages/reolink/camera_api.py", line 496, in get_settings
    response = await self.send(body)
  File "/usr/local/lib/python3.10/site-packages/reolink/camera_api.py", line 1652, in send
    if not await self.login():
  File "/usr/local/lib/python3.10/site-packages/reolink/camera_api.py", line 845, in login
    response = await self.send(body, param)
  File "/usr/local/lib/python3.10/site-packages/reolink/camera_api.py", line 1696, in send
    async with session.post(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 990, in _wrap_create_connection
    raise ClientConnectorSSLError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host 192.168.1.31:443 ssl:default [[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)]

**Comment by danielkaiser** [comment]
Could someone else try if my changes (#526) resolve the issue? At least for my setup (HA 2022.7.0 running in docker, RLC-410-5MP) the issue is fixed by this.

**Comment by Scope666** [comment]
> Could someone else try if my changes (#526) resolve the issue? At least for my setup (HA 2022.7.0 running in docker, RLC-410-5MP) the issue is fixed by this.

#526 works for me!!!

**Comment by cpainchaud** [comment]
V0.55 published

**Comment by landaisbenj** [comment]
> V0.55 published

You’re a beast. 

After update core and Reolink, Work for me on 2 camera for 4 … can i send some information ?

**Comment by ggasperino** [comment]
Works for my RLC-810As on core 2022.7.1 running on a Pi.

Thank you!!

**Comment by SmarterHomeLife** [comment]
0.55 fixes issue for me on 2022.7.1 with RLC-410 and E1 Zoom.

Thanks very much for all your work on this integration .

**Comment by skidank** [comment]
I'm having what appears to be a different problem since upgrading to 2022.7.x. I get the following error: 

`2022-07-09 04:08:37 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration reolink_dev: Unable to import component: No module named 'reolink'`

That's it. Any thoughts or additional information I can provide?

**Comment by msandrofJC** [comment]
A little more information. I'm running the HA docker container using podman on linux. I've also tried completely removing reolink_dev, then upgrading HA and installing back reolink_dev, but same error. No other HACS addons seem to have any problem (although I have only three).

**Comment by ckd77** [comment]
New fresh installation for testing on ha 2022.7.3 and new error.
My credentials are good, because I can access the camera via its https interface.

```
Traceback (most recent call last):
  File "/config/custom_components/reolink_dev/config_flow.py", line 70, in async_step_user
    self.info = await self.async_validate_input(self.hass, user_input)
  File "/config/custom_components/reolink_dev/config_flow.py", line 138, in async_validate_input
    if not await self.base.connect_api():
  File "/config/custom_components/reolink_dev/base.py", line 220, in connect_api
    if not await self._api.get_settings():
  File "/usr/local/lib/python3.10/site-packages/reolink/camera_api.py", line 496, in get_settings
    response = await self.send(body)
  File "/usr/local/lib/python3.10/site-packages/reolink/camera_api.py", line 1652, in send
    if not await self.login():
  File "/usr/local/lib/python3.10/site-packages/reolink/camera_api.py", line 845, in login
    response = await self.send(body, param)
  File "/usr/local/lib/python3.10/site-packages/reolink/camera_api.py", line 1721, in send
    raise CredentialsInvalidError()
reolink.exceptions.CredentialsInvalidError
```

**Comment by cpainchaud** [comment]
when that happens I need to reboot my own cameras

**Comment by jim-edwards** [comment]
Still having issues with older cameras since the Python update.  Getting an error: DH_KEY_TOO_SMALL.

**Comment by ryanbeales** [comment]
> I'm having what appears to be a different problem since upgrading to 2022.7.x. I get the following error:
> 
> `2022-07-09 04:08:37 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration reolink_dev: Unable to import component: No module named 'reolink'`
> 
> That's it. Any thoughts or additional information I can provide?

This one is related to this issue with pip in the home-assistant container https://github.com/home-assistant/core/pull/74922
The fix for this is targeted in 2022.7.4. I upgraded to 2022.7.3 this morning that that has broken the reocam integration, I saw a similar problem on a different HCAS integration. It's a fault with the home-assistant core.

**Comment by msandrofJC** [comment]
> This one is related to this issue with pip in the home-assistant container [home-assistant/core#74922](https://github.com/home-assistant/core/pull/74922)
> The fix for this is targeted in 2022.7.4. I upgraded to 2022.7.3 this morning that that has broken the reocam integration, I saw a similar problem on a different HCAS integration. It's a fault with the home-assistant core.

Thanks for the info, I'll wait for 2022.7.4 and try again!

**Comment by cxy7722** [comment]
> Still having issues with older cameras since the Python update. Getting an error: DH_KEY_TOO_SMALL. On devices RLC-420.

Also experiencing the same error with the same camera.

**Comment by cxy7722** [comment]
I was able to fix the DH_KEY_TOO_SMALL error by upgrading the firmware of my camera. There was a similar issue linked here: [https://github.com/fwestenberg/reolink_dev/issues/459]
