### ISSUE TITLE
calls media_source.async_resolve_media without passing an entity_id

### ISSUE THREAD

**Issue by garry0garry** [fwestenberg/reolink_dev#568]
HA v2022.9.2, reolink_dev v0.56. The problem:

```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 20:29:07 (1 occurrences)
Last logged: 20:29:07

Detected integration that calls media_source.async_resolve_media without passing an entity_id. Please report issue for media_source using this method at homeassistant/components/media_source/__init__.py, line 138: report("calls media_source.async_resolve_media without passing an entity_id")

```
I use the following cameras: Reolink RLC-511WA and Reolink RLC-520A.

https://github.com/home-assistant/core/issues/78318

**Comment by garry0garry** [comment]
HA v2022.9.4, reolink_dev v0.57.

Steps to reproduce:
1. Open HA:port/media-browser/browser
2. Open the Reolink IP Camera
3. Open the cam
4. Open video

Result:
```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 22:29:19 (1 occurrences)
Last logged: 22:29:19

Detected integration that calls media_source.async_resolve_media without passing an entity_id. Please report issue for media_source using this method at homeassistant/components/media_source/__init__.py, line 138: report("calls media_source.async_resolve_media without passing an entity_id")

```
```
Logger: root
Source: components/stream/worker.py:394
First occurred: 22:29:49 (1 occurrences)
Last logged: 22:29:49

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/homeassistant/homeassistant/components/stream/__init__.py", line 406, in _run_worker
    stream_worker(
  File "/usr/src/homeassistant/homeassistant/components/stream/worker.py", line 590, in stream_worker
    packet = next(container_packets)
  File "/usr/src/homeassistant/homeassistant/components/stream/worker.py", line 394, in __next__
    return self._next()
  File "av/container/input.pyx", line 181, in demux
  File "av/container/streams.pyx", line 63, in av.container.streams.StreamContainer.__getitem__
  File "av/container/streams.pyx", line 106, in av.container.streams.StreamContainer.get
IndexError: list index out of range

```

**Comment by malinovsku** [comment]
There is also an error when opening recordings from the camera via multimedia. After that, the integration is waiting for a restart in HACS
Reolink E1 Zoom v3.0.0.247_21040708
HA v2022.9.4, reolink_dev v0.57.

![pic](https://user-images.githubusercontent.com/34610364/190254588-5c19b81b-a1be-4b04-8f75-2193c7ab36b7.png)
