### ISSUE TITLE
Reolink RLC-420 unexpected error

### ISSUE THREAD

**Issue by adrianmihalko** [fwestenberg/reolink_dev#619]
Hi,

I followed installation steps, but I can't add my camera. I get unexpected error, I see nothing relevant in HA log.

<img width="542" alt="Screenshot 2023-01-26 at 22 16 14" src="https://user-images.githubusercontent.com/733361/214952195-f266b078-c008-44f0-8e67-673a0c21f4cc.png">

**Comment by Aprozz** [comment]
Same here with an RCL-820A

**Comment by Aprozz** [comment]
Here is the log file maybe somone will find the clue:

`Logger: custom_components.reolink_dev.config_flow
Source: custom_components/reolink_dev/base.py:229
Integration: Reolink IP camera ([documentation](https://github.com/fwestenberg/reolink_dev), [issues](https://github.com/fwestenberg/reolink_dev/issues))
First occurred: 11:18:51 (1 occurrences)
Last logged: 11:18:51

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/reolink_dev/config_flow.py", line 74, in async_step_user
    self.info = await self.async_validate_input(self.hass, user_input)
  File "/config/custom_components/reolink_dev/config_flow.py", line 142, in async_validate_input
    if not await self.base.connect_api():
  File "/config/custom_components/reolink_dev/base.py", line 229, in connect_api
    if not await self._api.get_settings():
  File "/usr/local/lib/python3.10/site-packages/reolink/camera_api.py", line 496, in get_settings
    response = await self.send(body)
  File "/usr/local/lib/python3.10/site-packages/reolink/camera_api.py", line 1661, in send
    if not await self.login():
  File "/usr/local/lib/python3.10/site-packages/reolink/camera_api.py", line 854, in login
    response = await self.send(body, param)
  File "/usr/local/lib/python3.10/site-packages/reolink/camera_api.py", line 1715, in send
    json_data = await response.text()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1080, in text
    await self.read()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1036, in read
    self._body = await self.content.read()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/streams.py", line 375, in read
    block = await self.readany()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/streams.py", line 397, in readany
    await self._wait("readany")
  File "/usr/local/lib/python3.10/site-packages/aiohttp/streams.py", line 303, in _wait
    with self._timer:
  File "/usr/local/lib/python3.10/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

**Comment by Aprozz** [comment]
it is working, after I enabeld Http with port 80 in the reolink settings

**Comment by adrianmihalko** [comment]
Yeah, enabling port 80 and now it works (still connecting with https 443). This should be in Readme.

**Comment by adrianmihalko** [comment]
> it is working, after I enabeld Http with port 80 in the reolink settings

Are you able to view video from HA? I see the camera image, but live video is not working:

<img width="960" alt="Screenshot 2023-01-28 at 19 53 28" src="https://user-images.githubusercontent.com/733361/215285736-9319c8d9-e374-4605-ba60-285d276c77ab.png">
