### ISSUE TITLE
Error while setting up reolink_dev platform for camera

### ISSUE THREAD

**Issue by Naesstrom** [fwestenberg/reolink_dev#73]
Installed this today with Hacs and rebooted.

Config for camera is:
```
- platform: reolink_dev
  host: 192.168.1.195
  username: !secret reolink_user
  password: !secret reolink_pass
  # name: optional, default Reolink Camera)
  name: frontdoor 
  # #stream: main or sub (optional, default main)
  stream: main
  # protocol: rtmp or rtsp (optional, default rtmp)
  protocol: rtmp
  # channel: NVR camera channel (optional, default 0)
  channel: 0
  # scan_interval: 5 (optional, default 30s)
  scan_interval: 5
```
Camera didn't show up and log shows me this error:
```
Logger: homeassistant.components.camera
Source: custom_components/reolink_dev/ReolinkPyPi/camera.py:372
Integration: Camera (documentation, issues)
First occurred: 12:45:09 PM (1 occurrences)
Last logged: 12:45:09 PM

Error while setting up reolink_dev platform for camera
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 494, in sock_connect
    return await fut
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 526, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.1.195', 80)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/reolink_dev/camera.py", line 70, in async_setup_platform
    await session.login(username, password)
  File "/config/custom_components/reolink_dev/ReolinkPyPi/camera.py", line 206, in login
    response = await self.send(body, param)
  File "/config/custom_components/reolink_dev/ReolinkPyPi/camera.py", line 372, in send
    async with session.post(url=self._url, json=body, params=param) as response:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 480, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 980, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 943, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.1.195:80 ssl:default [Connect call failed ('192.168.1.195', 80)]
```

**Comment by cigas4** [comment]
Completely same error for me also. Any ideas?

**Comment by XtremeOwnageDotCom** [comment]
https://github.com/fwestenberg/reolink/blob/master/custom_components/reolink_dev/ReolinkPyPi/camera.py Line 14, statically connects to the API on port 80.

Looking at the stack trace, that ip/port is not listening on your network, either due to..

1. Your local firewall.
2. Invalid IP address / other network issue.
3. Your camera is using HTTPs for the API, not on port 80.

**Comment by cigas4** [comment]
Hi,

I was trying to connect my new Reolink Lumus camera. Unfortunately, later I found out that this camera is not supporting RTMP/RTSP protocols. And also is not supporting browser user interface over IP address.. So this might be the reason that connection fails.

Specs of Lumus camera:
**Protocols & Standards:** SSL, TCP/IP, UDP, UPNP, SMTP, NTP, DHCP, DNS, DDNS, P2P
