### ISSUE TITLE
Interfering with Blink

### ISSUE THREAD

**Issue by elyobelyob** [fwestenberg/reolink_dev#79]
I have installed via HACS on HA Core. I also am using Blink cameras. Whenever I try and switch off my Blink cameras, the reolink component seems to interfere and force an error. I have uninstalled reolink and tested fine. Re-install and error returns. 

Here is my automation test 

- id: '1602577516768'
  alias: Cameras On Test
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /5
  condition: []
  action:
  - service: camera.disable_motion_detection
    entity_id: camera.blink_rear
  mode: single

Here is the error message (note the reolink error at the end)

2020-10-16 10:20:45 ERROR (MainThread) [homeassistant.components.automation.cameras_on_test] While executing automation automation.cameras_on_test
Traceback (most recent call last):
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/components/automation/__init__.py", line 426, in async_trigger
    await self.action_script.async_run(
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/script.py", line 985, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/script.py", line 239, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/script.py", line 247, in _async_step
    await getattr(
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/script.py", line 454, in _async_call_service_step
    await service_task
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 1335, in async_call
    task.result()
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 1374, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/homeassistant/custom_components/reolink_dev/camera.py", line 158, in handler_disable_motion_detection
    entity = component.get_entity(call.data.get(ATTR_ENTITY_ID))
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_component.py", line 99, in get_entity
    entity_obj = platform.entities.get(entity_id)
TypeError: unhashable type: 'list'

**Comment by fwestenberg** [comment]
Please check v0.8. Should be fixed!
